// Black-box Data API compatibility suite using the official Supabase client.
//
// Phase 00 spike artefact — see tasks/PHASE-00-FEASIBILITY.md. Kept because it
// is the concrete shape the Phase 03 suite should grow from, and because the
// compatibility matrix may only be promoted on evidence from tests like this.
//
//   npm install @supabase/supabase-js
//   SUPABASE_URL=... ANON_KEY=... TOKEN_A=... TOKEN_B=... node supabase-js-crud.mjs
//
// TARGET=supabase or TARGET=maludb selects which deployment is under test; the
// assertions are identical for both by design (docs/TESTING.md).
//
// Expects a tenant provisioned per specs/tenant-role-model.md with the
// `customers` table and `customer_count()` RPC from
// scripts/spike-provision-tenant.sh. Never commit real credentials.

import { createClient } from '@supabase/supabase-js';

const { SUPABASE_URL, ANON_KEY, TOKEN_A, TOKEN_B, TARGET = 'maludb' } = process.env;
if (!SUPABASE_URL || !ANON_KEY || !TOKEN_A || !TOKEN_B) {
  console.error('set SUPABASE_URL, ANON_KEY, TOKEN_A, TOKEN_B');
  process.exit(2);
}

const client = (token) =>
  createClient(SUPABASE_URL, ANON_KEY, {
    auth: { persistSession: false },
    global: { headers: token ? { Authorization: `Bearer ${token}` } : {} },
  });

const A = client(TOKEN_A);
const B = client(TOKEN_B);
const anon = client();

let pass = 0;
let fail = 0;
const ok = (name, cond, detail = '') => {
  if (cond) { pass++; console.log(`  PASS  ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}  ${JSON.stringify(detail)}`); }
};

console.log(`\nSupabase Data API compatibility — TARGET=${TARGET}\n`);

// clean slate for this run
await A.from('customers').delete().neq('name', '');
await B.from('customers').delete().neq('name', '');

let r = await A.from('customers').insert([
  { name: 'Acme Corp', email: 'a@acme.test' },
  { name: 'Globex', email: 'b@globex.test' },
]).select();
ok('insert (bulk) + .select()', !r.error && r.data?.length === 2, r.error);

r = await B.from('customers').insert({ name: 'Initech' }).select();
ok('insert as second user', !r.error && r.data?.length === 1, r.error);

r = await A.from('customers').select('*');
ok('select returns only own rows (RLS)', !r.error && r.data.length === 2, r.error || r.data);

r = await B.from('customers').select('*');
ok('second user isolated (RLS)', !r.error && r.data.length === 1, r.error || r.data);

r = await A.from('customers').update({ email: 'x@acme.test' }).eq('name', 'Acme Corp').select();
ok('update .eq()', !r.error && r.data?.[0]?.email === 'x@acme.test', r.error);

r = await A.from('customers').select('name').ilike('name', '%corp%');
ok('filter .ilike()', !r.error && r.data.length >= 1, r.error);

r = await A.from('customers').select('name').in('name', ['Globex', 'Nope']);
ok('filter .in()', !r.error && r.data.length === 1, r.error);

r = await A.from('customers').select('name').order('name', { ascending: false }).limit(2);
ok('order + limit', !r.error && r.data.length === 2, r.error);

r = await A.from('customers').select('name').range(0, 1);
ok('range', !r.error && r.data.length === 2, r.error);

r = await A.from('customers').select('*', { count: 'exact', head: true });
ok('count exact', !r.error && r.count === 2, r.error || r.count);

// finding 6: requires GENERATED BY DEFAULT AS IDENTITY, not ALWAYS
const first = (await A.from('customers').select('id').limit(1)).data?.[0]?.id;
r = await A.from('customers').upsert({ id: first, name: 'Acme Renamed' }).select();
ok('upsert', !r.error && r.data?.[0]?.name === 'Acme Renamed', r.error);

r = await A.rpc('customer_count');
ok('rpc', !r.error && typeof r.data === 'number', r.error || r.data);

r = await B.from('customers').update({ name: 'HIJACK' }).eq('name', 'Globex').select();
ok('cross-user update blocked (RLS)', !r.error && r.data.length === 0, r.error || r.data);

r = await anon.from('customers').select('*');
ok('anon cannot read (grant posture — finding 7)', !!r.error, r.error?.code);

r = await A.from('customers').select('no_such_column');
ok('error shape {code,message,details,hint}',
   !!r.error && ['code', 'message', 'details', 'hint'].every((k) => k in r.error), r.error);

const wrongKey = createClient(SUPABASE_URL, 'not-a-real-key', { auth: { persistSession: false } });
r = await wrongKey.from('customers').select('*');
ok('gateway rejects wrong apikey', !!r.error, r.error?.message);

r = await A.from('customers').delete().eq('name', 'Globex').select();
ok('delete', !r.error && r.data?.[0]?.name === 'Globex', r.error);

console.log(`\n  ${pass} passed, ${fail} failed\n`);
process.exit(fail ? 1 : 0);
