// Black-box compatibility suite, driven by the official Supabase client.
//
// AGENTS.md: "Add a black-box compatibility test using the official Supabase
// client when practical." Practical means this: the real client, over the real
// gateway, against a real provisioned tenant. Reimplementing what the client
// does in Python would test our understanding of it rather than the thing
// itself, and Phase 00 found three separate incompatibilities that only
// appeared when the actual client was in the loop.
//
// Reads MALUDB_URL and MALUDB_KEY from the environment, prints one JSON object
// per line, and exits non-zero if any case failed. The Python side asserts on
// that output; nothing here decides what "supported" means.

import { createClient } from '@supabase/supabase-js'

const url = process.env.MALUDB_URL
const key = process.env.MALUDB_KEY
if (!url || !key) {
  console.error('MALUDB_URL and MALUDB_KEY are required')
  process.exit(2)
}

const client = createClient(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
})

const results = []

async function check (name, fn) {
  try {
    await fn()
    results.push({ name, ok: true })
  } catch (error) {
    results.push({ name, ok: false, error: String(error && error.message || error) })
  }
}

function expect (condition, message) {
  if (!condition) throw new Error(message)
}

function assertNoError (result, where) {
  if (result.error) {
    throw new Error(`${where}: ${result.error.message} (${result.error.code || 'no code'})`)
  }
}

// -- the proof milestone --------------------------------------------------

await check('select', async () => {
  const result = await client.from('customers').select('*')
  assertNoError(result, 'select')
  expect(Array.isArray(result.data), 'select did not return an array')
})

await check('insert', async () => {
  const result = await client
    .from('customers')
    .insert({ name: 'Ada', tier: 'free' })
    .select()
  assertNoError(result, 'insert')
  expect(result.data.length === 1, 'insert did not return the inserted row')
  expect(result.data[0].name === 'Ada', 'insert returned the wrong row')
})

await check('insert many', async () => {
  const result = await client
    .from('customers')
    .insert([{ name: 'Grace', tier: 'paid' }, { name: 'Alan', tier: 'free' }])
    .select()
  assertNoError(result, 'insert many')
  expect(result.data.length === 2, 'insert many returned the wrong count')
})

await check('update', async () => {
  const result = await client
    .from('customers')
    .update({ tier: 'paid' })
    .eq('name', 'Ada')
    .select()
  assertNoError(result, 'update')
  expect(result.data[0].tier === 'paid', 'update did not take')
})

await check('upsert', async () => {
  // GENERATED BY DEFAULT AS IDENTITY, not ALWAYS: Phase 00 finding 5 was that
  // GENERATED ALWAYS breaks exactly this call.
  const existing = await client.from('customers').select('id').eq('name', 'Ada').single()
  assertNoError(existing, 'upsert lookup')
  const result = await client
    .from('customers')
    .upsert({ id: existing.data.id, name: 'Ada Lovelace', tier: 'paid' })
    .select()
  assertNoError(result, 'upsert')
  expect(result.data[0].name === 'Ada Lovelace', 'upsert did not update in place')
})

await check('filters', async () => {
  const eq = await client.from('customers').select('*').eq('tier', 'free')
  assertNoError(eq, 'eq')
  expect(eq.data.every((row) => row.tier === 'free'), 'eq returned another tier')

  const neq = await client.from('customers').select('*').neq('tier', 'free')
  assertNoError(neq, 'neq')
  expect(neq.data.every((row) => row.tier !== 'free'), 'neq returned the excluded tier')

  const like = await client.from('customers').select('*').like('name', 'A%')
  assertNoError(like, 'like')
  expect(like.data.every((row) => row.name.startsWith('A')), 'like matched the wrong rows')

  const inList = await client.from('customers').select('*').in('tier', ['free', 'paid'])
  assertNoError(inList, 'in')
  expect(inList.data.length >= 3, 'in returned too few rows')
})

await check('ordering', async () => {
  const result = await client.from('customers').select('name').order('name', { ascending: true })
  assertNoError(result, 'order')
  const names = result.data.map((row) => row.name)
  const sorted = [...names].sort()
  expect(JSON.stringify(names) === JSON.stringify(sorted), 'order did not sort')
})

await check('range and limit', async () => {
  const limited = await client.from('customers').select('*').limit(2)
  assertNoError(limited, 'limit')
  expect(limited.data.length === 2, 'limit was ignored')

  const ranged = await client.from('customers').select('*').order('id').range(1, 2)
  assertNoError(ranged, 'range')
  expect(ranged.data.length === 2, 'range returned the wrong window')
})

await check('count', async () => {
  const result = await client.from('customers').select('*', { count: 'exact', head: true })
  assertNoError(result, 'count')
  expect(typeof result.count === 'number', 'count was not returned')
  expect(result.count >= 3, 'count was too low')
})

await check('rpc', async () => {
  const result = await client.rpc('customer_count')
  assertNoError(result, 'rpc')
  expect(typeof result.data === 'number', 'rpc did not return a number')
})

await check('delete', async () => {
  const result = await client.from('customers').delete().eq('name', 'Alan').select()
  assertNoError(result, 'delete')
  expect(result.data.length === 1, 'delete removed the wrong number of rows')
})

// -- the properties the platform adds -------------------------------------

await check('rls hides another tenant-scoped row', async () => {
  // `secrets` has RLS enabled and a policy no anonymous caller satisfies.
  // Phase 00 finding 7: with a grant this is an empty set, and without one it
  // is 42501. Applications distinguish the two, so the grant posture is part
  // of compatibility rather than an implementation detail.
  const result = await client.from('secrets').select('*')
  assertNoError(result, 'rls select')
  expect(result.data.length === 0, 'RLS did not filter the rows')
})

await check('a table created after the worker started is visible', async () => {
  // Phase 00 finding 3, through the client rather than through curl.
  const result = await client.from('late_table').select('*')
  assertNoError(result, 'late table select')
  expect(Array.isArray(result.data), 'late table was not queryable')
})

await check('extension functions are not exposed as rpc', async () => {
  // ADR-018. gen_salt was reachable as /rpc/gen_salt during the Phase 00 spike.
  const result = await client.rpc('gen_salt', { type: 'bf' })
  expect(result.error !== null, 'gen_salt was callable as RPC')
})

// -- Auth (Phase 04 slice 2) ---------------------------------------------
//
// Driven through the same client and the same gateway, so what is proven is
// that `supabase.auth` works against MaluDB -- not that our idea of GoTrue's
// wire format is right.

const email = `user-${Date.now()}-${Math.floor(Math.random() * 1e6)}@example.com`
const password = 'correct-horse-battery-staple-42'
let session = null

await check('auth signup', async () => {
  const result = await client.auth.signUp({ email, password })
  assertNoError(result, 'signUp')
  expect(result.data.user !== null, 'signUp returned no user')
  expect(result.data.user.email === email, 'signUp returned a different address')
})

await check('auth signin password', async () => {
  const result = await client.auth.signInWithPassword({ email, password })
  assertNoError(result, 'signInWithPassword')
  session = result.data.session
  expect(session !== null, 'sign-in returned no session')
  expect(typeof session.access_token === 'string', 'no access token')
  expect(typeof session.refresh_token === 'string', 'no refresh token')
})

await check('auth token carries the claims RLS needs', async () => {
  // The claims PostgREST turns into request.jwt.claims, which auth.uid() and
  // auth.role() read. A token missing either is a session that authenticates
  // and then fails every policy closed.
  const [, payload] = session.access_token.split('.')
  const claims = JSON.parse(Buffer.from(payload, 'base64url').toString())
  expect(typeof claims.sub === 'string', 'no sub claim')
  expect(claims.role === 'authenticated', `role claim was ${claims.role}`)
  expect(claims.aud === 'authenticated', `aud claim was ${claims.aud}`)
})

await check('auth get user', async () => {
  const result = await client.auth.getUser(session.access_token)
  assertNoError(result, 'getUser')
  expect(result.data.user.email === email, 'getUser returned a different user')
})

await check('auth session refresh', async () => {
  const result = await client.auth.refreshSession({ refresh_token: session.refresh_token })
  assertNoError(result, 'refreshSession')
  expect(result.data.session !== null, 'refresh returned no session')

  // Deliberately not asserting the access token *changed*. An HS256 JWT is a
  // pure function of its claims, so refreshing inside the same second returns
  // a byte-identical token -- observed, not assumed. The property that matters
  // is that the refreshed session works, so it is checked by using it.
  const refreshed = result.data.session.access_token
  expect(typeof refreshed === 'string' && refreshed.length > 0, 'no access token after refresh')
  const check2 = await client.auth.getUser(refreshed)
  assertNoError(check2, 'getUser with the refreshed token')
  expect(check2.data.user.email === email, 'refreshed token identified a different user')
})

await check('auth signout', async () => {
  const scoped = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } })
  await scoped.auth.signInWithPassword({ email, password })
  const result = await scoped.auth.signOut()
  expect(!result.error, `signOut: ${result.error && result.error.message}`)
})

await check('a wrong password is refused', async () => {
  const result = await client.auth.signInWithPassword({ email, password: 'not-the-password' })
  expect(result.error !== null, 'a wrong password produced a session')
  expect(result.data.session === null, 'a wrong password produced a session')
})

for (const row of results) console.log(JSON.stringify(row))
process.exit(results.every((row) => row.ok) ? 0 : 1)
