"""Direct SQL for paid projects: the admin role, and what it may not do.

`specs/tenant-role-model.md` has described `mldb_<ref>_admin` as "the role for
paid direct SQL" since Phase 02, and until now it had no privilege on `public`
at all -- not CREATE, not USAGE -- and was NOLOGIN with a stored password it
could never use. A customer connecting as it got `permission denied for schema
public`. Nothing noticed because every table in a tenant, including in every
test, was created by the platform superuser.

This is a privilege grant, so the negatives carry more weight than the
positives: what matters is not that the role can now create a table, but that it
still cannot reach another tenant, cannot escalate, and cannot log in at all
unless the plan says so.
"""

from __future__ import annotations

import psycopg
import pytest

from services.control_plane import db, entitlements, provisioning
from tests.conftest import requires_db
from tests.test_provisioning import (
    ADMIN_DSN,
    _provision,
    _tenant_dsn,
    requires_maludb_core,
)

pytestmark = [requires_db]
requires_node = pytest.mark.skipif(not ADMIN_DSN, reason="MALUDB_NODE_ADMIN_DSN is unset")


@pytest.fixture
def paid_project(admin_conn, key_ring, project_factory):
    """A provisioned tenant whose plan entitles it to direct SQL."""

    def make(ref: str, *, direct_access=True):
        project_id = project_factory(ref)
        with db.connection() as conn:
            node = db.one(
                conn,
                "INSERT INTO nodes (name, hostname, internal_host, node_pool, status) "
                "VALUES ('ds-node','ds.example','ds.internal','shared','active') "
                "ON CONFLICT (name) DO UPDATE SET status='active' RETURNING id",
            )["id"]
            # Its own plan row per project: `plans.code` is unique, so two paid
            # projects in one test cannot both be renamed to `starter`.
            # `direct_database_access` is set explicitly rather than inherited
            # from a tier, which is also the more honest test -- it is the field
            # provisioning actually reads.
            db.execute(
                conn,
                "UPDATE plans SET config_json = %s WHERE id = "
                "(SELECT plan_id FROM projects WHERE id = %s)",
                (psycopg.types.json.Jsonb({"direct_database_access": direct_access}), project_id),
            )
            db.execute(conn, "UPDATE projects SET node_id = %s WHERE id = %s", (node, project_id))
            conn.commit()
        names, passwords = _provision(project_id, admin_conn, key_ring, ref)
        return project_id, names, passwords

    return make


def _as_admin(names, passwords):
    return psycopg.connect(_tenant_dsn(names.database, names.admin, passwords["admin"]))


# -- the capability that was listed and did not work -----------------------


@requires_node
@requires_maludb_core
def test_a_paid_project_can_connect_and_create_a_table(paid_project):
    """The gap: `permission denied for schema public`, for the role the spec
    calls the one for paid direct SQL."""
    _, names, passwords = paid_project("ds000001")
    with _as_admin(names, passwords) as conn:
        conn.execute("CREATE TABLE public.customer_made (id bigint GENERATED BY DEFAULT AS "
                     "IDENTITY PRIMARY KEY, body text)")
        conn.execute("INSERT INTO public.customer_made (body) VALUES ('hello')")
        conn.commit()
        with conn.cursor() as cur:
            cur.execute("SELECT body FROM public.customer_made")
            assert [r[0] for r in cur.fetchall()] == ["hello"]


@requires_node
@requires_maludb_core
def test_a_table_the_customer_creates_is_reachable_by_their_own_data_api(paid_project):
    """The half that would have been a worse bug than the one it replaced.

    `ALTER DEFAULT PRIVILEGES` only affects objects created by the role it
    names, and bootstrap 004 named only the bootstrapping role. So a table the
    customer created through direct SQL would carry no grant for anon or
    authenticated -- and Phase 00 finding 7 established that no grant surfaces
    as `42501 permission denied`, not as an empty set. Their first table would
    be invisible to their own API, with an error that says nothing about grants.
    """
    _, names, passwords = paid_project("ds000002")
    with _as_admin(names, passwords) as conn:
        conn.execute("CREATE TABLE public.via_direct_sql (id int)")
        conn.execute("INSERT INTO public.via_direct_sql (id) VALUES (1)")
        conn.commit()

    api = psycopg.connect(_tenant_dsn(names.database, names.authenticator,
                                      passwords["authenticator"]))
    with api as conn:
        conn.execute("SET ROLE authenticated")
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM public.via_direct_sql")
            assert [r[0] for r in cur.fetchall()] == [1]


@requires_node
@requires_maludb_core
def test_the_customer_can_alter_and_drop_what_they_created(paid_project):
    """Creating a table you cannot then change is not a usable capability."""
    _, names, passwords = paid_project("ds000003")
    with _as_admin(names, passwords) as conn:
        conn.execute("CREATE TABLE public.mine (id int)")
        conn.execute("ALTER TABLE public.mine ADD COLUMN note text")
        conn.execute("CREATE INDEX mine_note_idx ON public.mine (note)")
        conn.execute("DROP TABLE public.mine")
        conn.commit()


# -- ADR-005: the capability is gated by the plan --------------------------


@requires_node
@requires_maludb_core
def test_a_free_project_cannot_log_in_at_all(paid_project):
    """ADR-005 makes direct SQL a paid capability, and this is the mechanism.
    A free project's admin role keeps its stored password and cannot use it."""
    _, names, passwords = paid_project("ds000004", direct_access=False)
    with pytest.raises(psycopg.OperationalError):
        psycopg.connect(_tenant_dsn(names.database, names.admin, passwords["admin"]))


@requires_node
@requires_maludb_core
def test_enabling_access_does_not_mint_a_new_credential(paid_project, admin_conn):
    """The password is stored from the first provisioning run. A customer who
    already has it must not get a different one on upgrade."""
    project_id, names, passwords = paid_project("ds000005", direct_access=False)
    provisioning.set_direct_sql_access(admin_conn, names, enabled=True)

    with _as_admin(names, passwords) as conn, conn.cursor() as cur:
        cur.execute("SELECT current_user")
        assert cur.fetchone()[0] == names.admin


@requires_node
@requires_maludb_core
def test_disabling_access_stops_new_connections(paid_project, admin_conn):
    _, names, passwords = paid_project("ds000006")
    with _as_admin(names, passwords) as conn:
        conn.execute("SELECT 1")

    provisioning.set_direct_sql_access(admin_conn, names, enabled=False)
    with pytest.raises(psycopg.OperationalError):
        psycopg.connect(_tenant_dsn(names.database, names.admin, passwords["admin"]))


@requires_node
@requires_maludb_core
def test_provisioning_applies_the_plan_without_an_operator(paid_project, admin_conn):
    """A paid project whose admin role stayed NOLOGIN would have been sold a
    capability it did not have."""
    _, paid_names, _ = paid_project("ds000007", direct_access=True)
    _, free_names, _ = paid_project("ds000008", direct_access=False)
    assert provisioning.has_direct_sql_access(admin_conn, paid_names) is True
    assert provisioning.has_direct_sql_access(admin_conn, free_names) is False


# -- the negatives, which matter more than the positives -------------------


@requires_node
@requires_maludb_core
def test_the_admin_role_is_still_not_elevated(paid_project, admin_conn):
    """A grant of CREATE on one schema must not have become anything else."""
    _, names, _ = paid_project("ds000009")
    with admin_conn.cursor() as cur:
        cur.execute(
            "SELECT rolsuper, rolcreatedb, rolcreaterole, rolbypassrls, rolreplication "
            "FROM pg_roles WHERE rolname = %s", (names.admin,)
        )
        attributes = cur.fetchone()
    assert not any(attributes.values() if hasattr(attributes, "values") else attributes)


@requires_node
@requires_maludb_core
def test_the_admin_role_cannot_reach_another_tenant(paid_project):
    """ADR-014's lockdown is what makes a login role safe on a shared node, and
    granting one CONNECT to its own database must not have widened that."""
    _, a_names, a_passwords = paid_project("ds00000a")
    _, b_names, _ = paid_project("ds00000b")
    with pytest.raises(psycopg.OperationalError):
        psycopg.connect(_tenant_dsn(b_names.database, a_names.admin, a_passwords["admin"]))


@requires_node
@requires_maludb_core
def test_the_admin_role_does_not_own_the_schema(paid_project):
    """A customer that owned `public` could drop it, taking the auth helpers and
    the platform's bookkeeping with it (ADR-004)."""
    _, names, passwords = paid_project("ds00000c")
    with _as_admin(names, passwords) as conn:
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            conn.execute("DROP SCHEMA public CASCADE")
        conn.rollback()
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            conn.execute("DROP SCHEMA maludb_platform CASCADE")
        conn.rollback()


@requires_node
@requires_maludb_core
def test_the_admin_role_cannot_read_the_platform_bookkeeping(paid_project):
    """`maludb_platform` holds the bootstrap ledger, and it is not customer
    surface -- the same property Phase 02 asserted for anon and authenticated."""
    _, names, passwords = paid_project("ds00000d")
    with _as_admin(names, passwords) as conn, pytest.raises(psycopg.errors.InsufficientPrivilege):
        conn.execute("SELECT * FROM maludb_platform.bootstrap_migrations")


@requires_node
@requires_maludb_core
def test_the_admin_role_cannot_install_extensions(paid_project):
    """ADR-010: extensions are allowlisted and the platform installs them."""
    _, names, passwords = paid_project("ds00000e")
    with _as_admin(names, passwords) as conn, pytest.raises(psycopg.errors.InsufficientPrivilege):
        conn.execute("CREATE EXTENSION IF NOT EXISTS pg_stat_statements")


@requires_node
@requires_maludb_core
def test_the_admin_role_cannot_undo_the_adr_018_hardening(paid_project):
    """Extension functions must stay off the Data API even for a paid customer
    with direct SQL: `anon` is shared, and a grant here is a grant for the
    project's own public API."""
    _, names, passwords = paid_project("ds00000f")
    with _as_admin(names, passwords) as conn, pytest.raises(psycopg.errors.InsufficientPrivilege):
        conn.execute("GRANT EXECUTE ON FUNCTION public.gen_salt(text) TO anon")


def test_the_free_plan_still_says_no_direct_access():
    assert entitlements.resolve("free", None).direct_database_access is False
    assert entitlements.resolve("starter", None).direct_database_access is True
