"""Storage accounting and quota enforcement.

The classification is pure and tested as such. The enforcement is not: whether
a revoke actually stops a write is a property of PostgreSQL's privilege system,
and asserting that the right SQL was issued would only test that I can spell
REVOKE. So the restriction tests connect as the tenant's own API role and try to
write.

Restriction is the most customer-visible thing in this phase and the closest to
irreversible-feeling, so these lean on the recovery paths: that a restricted
project can still read, can still delete its way back under, and gets its writes
returned when it does.
"""

from __future__ import annotations

import psycopg
import pytest

from services.control_plane import db, entitlements, storage
from tests.conftest import requires_db
from tests.test_provisioning import (
    ADMIN_DSN,
    _provision,
    _tenant_admin_dsn,
    _tenant_dsn,
    requires_maludb_core,
)

pytestmark = [requires_db]
requires_node = pytest.mark.skipif(not ADMIN_DSN, reason="MALUDB_NODE_ADMIN_DSN is unset")

MB = 1024 * 1024


# -- classification --------------------------------------------------------


def test_a_fresh_project_uses_none_of_its_quota():
    """ADR-015: every tenant carries maludb_core before a customer row.
    Counting it would spend a chunk of a free project's quota at creation, and
    reporting it as negative would be worse."""
    usage = storage.classify(20 * MB, 500 * MB, baseline_bytes=23_639_731)
    assert usage.billable_bytes == 0
    assert usage.state == storage.OK


def test_a_baseline_larger_than_reality_would_hide_all_usage():
    """The bug this module shipped with in its first draft: the constant was set
    to 23 MiB against a real baseline of 23,639,731 bytes (22.5 MiB), so every
    project floored to zero usage and no quota could ever be exceeded. The
    fallback is now deliberately *below* the measured figure."""
    real_baseline = 23_639_731
    assert storage.BASELINE_BYTES < real_baseline, (
        "the fallback baseline must under-subtract: over-subtracting hides usage"
    )
    over_quota = real_baseline + 600 * MB
    assert storage.classify(over_quota, 500 * MB).state == storage.RESTRICTED


def test_the_recorded_baseline_is_preferred_over_the_constant():
    """The figure moves with the extension version, so a project's own recorded
    baseline is the accurate one."""
    generous = storage.classify(100 * MB, 500 * MB, baseline_bytes=90 * MB)
    assert generous.billable_bytes == 10 * MB


def test_the_quota_is_net_of_the_extension_baseline():
    """A project holding exactly its quota of customer data is at 100%, not
    over -- the baseline is not the customer's."""
    usage = storage.classify(storage.BASELINE_BYTES + 500 * MB, 500 * MB)
    assert usage.billable_bytes == 500 * MB
    assert usage.state == storage.RESTRICTED


def test_the_warning_arrives_before_the_restriction():
    """A warning that arrives with the restriction is not a warning."""
    below = storage.classify(storage.BASELINE_BYTES + 399 * MB, 500 * MB)
    at = storage.classify(storage.BASELINE_BYTES + 400 * MB, 500 * MB)
    assert below.state == storage.OK
    assert at.state == storage.WARNING
    assert at.fraction < 1.0


def test_the_raw_measurement_is_preserved_not_just_the_verdict():
    """Storing an adjusted figure would leave nothing able to answer what the
    database actually weighs on disk."""
    usage = storage.classify(123 * MB, 500 * MB)
    assert usage.gross_bytes == 123 * MB


def test_a_project_with_no_quota_is_never_restricted():
    """Failing open here is deliberate: reaching this with no quota means the
    entitlement resolver already misbehaved, and cutting off writes on a
    configuration error is the wrong direction."""
    assert storage.classify(10 * 1024 * MB, 0).state == storage.OK


# -- the restriction, against a real tenant --------------------------------


@pytest.fixture
def storage_project(admin_conn, key_ring, project_factory):
    """A provisioned tenant with a table its API roles can write."""

    def make(ref: str):
        project_id = project_factory(ref)
        with db.connection() as conn:
            node = db.one(
                conn,
                "INSERT INTO nodes (name, hostname, internal_host, node_pool, status) "
                "VALUES ('st-node','st.example','st.internal','shared','active') "
                "ON CONFLICT (name) DO UPDATE SET status='active' RETURNING id",
            )["id"]
            db.execute(conn, "UPDATE projects SET node_id = %s WHERE id = %s", (node, project_id))
            conn.commit()
        names, passwords = _provision(project_id, admin_conn, key_ring, ref)

        with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
            tenant.execute("CREATE TABLE public.notes (id bigint GENERATED BY DEFAULT AS IDENTITY "
                           "PRIMARY KEY, body text)")
            tenant.execute("INSERT INTO public.notes (body) VALUES ('existing')")
            tenant.commit()
        return project_id, names, passwords

    return make


def _as_api_role(names, passwords, role: str = "authenticated"):
    conn = psycopg.connect(_tenant_dsn(names.database, names.authenticator,
                                       passwords["authenticator"]))
    conn.execute(f"SET ROLE {role}")
    return conn


@requires_node
@requires_maludb_core
def test_a_restricted_project_cannot_insert_or_update(storage_project):
    """Asserting the SQL was issued would only test that I can spell REVOKE.
    This asks PostgreSQL."""
    _, names, passwords = storage_project("st000001")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)

    with _as_api_role(names, passwords) as conn:
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            conn.execute("INSERT INTO public.notes (body) VALUES ('blocked')")
        conn.rollback()
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            conn.execute("UPDATE public.notes SET body = 'blocked'")
        conn.rollback()


@requires_node
@requires_maludb_core
def test_a_restricted_project_can_still_read(storage_project):
    """Cutting off reads punishes a customer for a condition they need to see
    in order to fix, and stops them exporting their data."""
    _, names, passwords = storage_project("st000002")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)

    with _as_api_role(names, passwords) as conn, conn.cursor() as cur:
        cur.execute("SELECT body FROM public.notes")
        assert [r[0] for r in cur.fetchall()] == ["existing"]


@requires_node
@requires_maludb_core
def test_a_restricted_project_can_delete_its_way_back(storage_project):
    """The recovery path. Revoking DELETE would make the restriction a trap
    only support could unlock."""
    _, names, passwords = storage_project("st000003")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)

    with _as_api_role(names, passwords) as conn:
        conn.execute("DELETE FROM public.notes")
        conn.commit()
        with conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM public.notes")
            assert cur.fetchone()[0] == 0


@requires_node
@requires_maludb_core
def test_a_table_created_while_restricted_is_not_writable(storage_project):
    """The half that bites. Bootstrap 004 grants ALL on future tables, so
    without revoking the default privilege a restricted project could create a
    table and walk straight back out of its restriction."""
    _, names, passwords = storage_project("st000004")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)

    # Created by the platform role, which is the only thing that can create
    # tables in a tenant today: nothing grants mldb_<ref>_admin CREATE on
    # `public`, despite specs/tenant-role-model.md describing it as the role for
    # paid direct SQL. Recorded as a carried-forward gap; using the role that
    # actually creates tables is what makes this test exercise the real path.
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        tenant.execute("CREATE TABLE public.escape (id int)")
        tenant.commit()

    with _as_api_role(names, passwords) as conn, pytest.raises(psycopg.errors.InsufficientPrivilege):
        conn.execute("INSERT INTO public.escape (id) VALUES (1)")


@requires_node
@requires_maludb_core
def test_releasing_restores_writes_including_on_tables_made_while_restricted(storage_project):
    """Restriction has to be fully reversible, or it is a one-way door."""
    _, names, passwords = storage_project("st000005")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        tenant.execute("CREATE TABLE public.made_while_restricted (id int)")
        tenant.commit()
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.release(tenant)

    with _as_api_role(names, passwords) as conn:
        conn.execute("INSERT INTO public.notes (body) VALUES ('allowed again')")
        conn.execute("INSERT INTO public.made_while_restricted (id) VALUES (1)")
        conn.commit()


@requires_node
@requires_maludb_core
def test_service_role_keeps_writing_while_restricted(storage_project):
    """Reachable only from the project's own backend, and the most likely thing
    to be running the cleanup that gets it back under quota."""
    _, names, passwords = storage_project("st000006")
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant:
        storage.restrict(tenant)

    with _as_api_role(names, passwords, role="service_role") as conn:
        conn.execute("INSERT INTO public.notes (body) VALUES ('backend cleanup')")
        conn.commit()


# -- measurement and the state machine -------------------------------------


@requires_node
@requires_maludb_core
def test_measuring_records_the_size_and_leaves_a_healthy_project_alone(storage_project, admin_conn):
    project_id, names, passwords = storage_project("st000007")

    def tenant_connect(database):
        return psycopg.connect(_tenant_admin_dsn(database))

    with db.connection() as conn:
        usage = storage.evaluate(
            conn, admin_conn, project_id=project_id, tenant_connect=tenant_connect
        )
        row = db.one(
            conn,
            "SELECT database_bytes, database_measured_at, storage_state FROM projects WHERE id = %s",
            (project_id,),
        )

    assert usage.state == storage.OK
    assert row["database_bytes"] > 0
    assert row["database_measured_at"] is not None
    assert row["storage_state"] == storage.OK
    with _as_api_role(names, passwords) as conn:
        conn.execute("INSERT INTO public.notes (body) VALUES ('still fine')")
        conn.commit()


@requires_node
@requires_maludb_core
def test_exceeding_the_quota_restricts_and_audits(storage_project, admin_conn):
    """The end-to-end path, driven by setting a quota the project already
    exceeds rather than by writing a gigabyte of rows."""
    project_id, names, passwords = storage_project("st000008")
    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE plans SET config_json = %s WHERE id = "
            "(SELECT plan_id FROM projects WHERE id = %s)",
            (psycopg.types.json.Jsonb({"limits": {"database_storage_bytes": 1}}), project_id),
        )
        conn.commit()

    def tenant_connect(database):
        return psycopg.connect(_tenant_admin_dsn(database))

    with db.connection() as conn:
        usage = storage.evaluate(
            conn, admin_conn, project_id=project_id, tenant_connect=tenant_connect
        )
        assert usage.state == storage.RESTRICTED
        row = db.one(
            conn, "SELECT storage_state, storage_restricted_at FROM projects WHERE id = %s",
            (project_id,),
        )
        events = db.query(
            conn, "SELECT event_type, detail_json FROM audit_events WHERE project_id = %s",
            (project_id,),
        )

    assert row["storage_state"] == storage.RESTRICTED
    assert row["storage_restricted_at"] is not None
    assert [e["event_type"] for e in events] == ["storage.restricted"]
    assert events[0]["detail_json"]["quota_bytes"] == 1, "the numbers behind the decision"

    with _as_api_role(names, passwords) as conn, pytest.raises(psycopg.errors.InsufficientPrivilege):
        conn.execute("INSERT INTO public.notes (body) VALUES ('over quota')")


@requires_node
@requires_maludb_core
def test_getting_back_under_releases_the_restriction(storage_project, admin_conn):
    project_id, names, passwords = storage_project("st000009")

    def tenant_connect(database):
        return psycopg.connect(_tenant_admin_dsn(database))

    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE plans SET config_json = %s WHERE id = "
            "(SELECT plan_id FROM projects WHERE id = %s)",
            (psycopg.types.json.Jsonb({"limits": {"database_storage_bytes": 1}}), project_id),
        )
        conn.commit()
        storage.evaluate(conn, admin_conn, project_id=project_id, tenant_connect=tenant_connect)

        # The customer upgrades, or deletes enough. Either way the next pass
        # must give the writes back.
        db.execute(
            conn,
            "UPDATE plans SET config_json = %s WHERE id = "
            "(SELECT plan_id FROM projects WHERE id = %s)",
            (psycopg.types.json.Jsonb({"limits": {"database_storage_bytes": 10 * 1024 * MB}}),
             project_id),
        )
        conn.commit()
        usage = storage.evaluate(
            conn, admin_conn, project_id=project_id, tenant_connect=tenant_connect
        )
        events = db.query(
            conn, "SELECT event_type FROM audit_events WHERE project_id = %s ORDER BY id",
            (project_id,),
        )

    assert usage.state == storage.OK
    assert [e["event_type"] for e in events] == ["storage.restricted", "storage.released"]
    with _as_api_role(names, passwords) as conn:
        conn.execute("INSERT INTO public.notes (body) VALUES ('writing again')")
        conn.commit()


@requires_node
@requires_maludb_core
def test_re_measuring_an_already_restricted_project_does_not_re_audit(storage_project, admin_conn):
    """A pass that runs every few minutes must not write an audit event every
    few minutes, or the log that explains a restriction becomes the noise that
    hides it."""
    project_id, _, _ = storage_project("st00000a")

    def tenant_connect(database):
        return psycopg.connect(_tenant_admin_dsn(database))

    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE plans SET config_json = %s WHERE id = "
            "(SELECT plan_id FROM projects WHERE id = %s)",
            (psycopg.types.json.Jsonb({"limits": {"database_storage_bytes": 1}}), project_id),
        )
        conn.commit()
        for _ in range(3):
            storage.evaluate(conn, admin_conn, project_id=project_id, tenant_connect=tenant_connect)
        events = db.query(
            conn, "SELECT event_type FROM audit_events WHERE project_id = %s", (project_id,)
        )
    assert len(events) == 1


@requires_db
def test_projects_are_measured_least_recently_first(db_pool):
    """A pass with a limit must not keep re-measuring the same projects while
    others go years without."""
    with db.connection() as conn:
        assert storage.due_for_measurement(conn) == []


def test_the_free_quota_is_a_real_number():
    """`database_storage_bytes` was null in the spec until slice 1. A null read
    as no-limit would make the free tier unbounded, which is the thing this
    slice exists to prevent."""
    assert entitlements.resolve("free", None).database_storage_bytes > 0
