"""Phase 03's proof milestone, run with the official Supabase client.

    const client = createClient('https://<ref>.maludb.com', '<publishable-key>')
    const { data, error } = await client.from('customers').select('*')

Everything in the path is real: a tenant provisioned by Phase 02 code, hardened
by its bootstrap, served by PostgREST 14.17, reached through the Phase 03
gateway over a hostname that actually resolves, authenticated with a key issued
by slice 1.

Reimplementing the client in Python would test our reading of its behaviour
rather than the behaviour. Phase 00 found three incompatibilities that only
appeared with the real client in the loop -- `GENERATED ALWAYS` breaking
`.upsert()`, the schema cache hiding new tables, and extension functions
appearing as RPC -- and each is asserted here as a regression test.
"""

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import psycopg
import pytest
import uvicorn

from services.control_plane import api_keys, auth_workers, db, mail, tenant_bootstrap, workers
from services.gateway.app import Gateway, create_app
from tests.conftest import TEST_PEPPER, requires_db
from tests.test_provisioning import (
    ADMIN_DSN,
    _provision_core,
    _tenant_admin_dsn,
    requires_maludb_core,
)

# Fixed so the hosts entry is stable and can be made once during environment
# setup rather than mutated per test run.
COMPAT_REF = "cmpt0001"
GATEWAY_PORT = 28110
POSTGREST_PORT = 28432
GOTRUE_PORT = 28433
MAILBOX_PORT = 28434

COMPAT_DIR = Path(__file__).parent / "compat"
POSTGREST_BIN = os.environ.get("MALUDB_POSTGREST_BIN", "postgrest")
GOTRUE_BIN = os.environ.get("MALUDB_GOTRUE_BIN", "gotrue")


def _resolves(hostname: str) -> bool:
    try:
        socket.getaddrinfo(hostname, None)
    except socket.gaierror:
        return False
    return True


requires_node = pytest.mark.skipif(shutil.which("node") is None, reason="node is not installed")
requires_client = pytest.mark.skipif(
    not (COMPAT_DIR / "node_modules").exists(),
    reason="run `npm install` in tests/compat",
)
requires_postgrest = pytest.mark.skipif(
    shutil.which(POSTGREST_BIN) is None and not os.path.exists(POSTGREST_BIN),
    reason="PostgREST binary not available",
)
requires_hostname = pytest.mark.skipif(
    not _resolves(f"{COMPAT_REF}.maludb.local"),
    reason=f"add '127.0.0.1 {COMPAT_REF}.maludb.local' to /etc/hosts",
)

pytestmark = [
    requires_db,
    pytest.mark.skipif(not ADMIN_DSN, reason="MALUDB_NODE_ADMIN_DSN is unset"),
    requires_maludb_core,
    requires_postgrest,
    requires_node,
    requires_client,
    requires_hostname,
]


# The schema a customer would arrive with. Created as the tenant admin, which
# is how a dashboard SQL editor or a migration tool reaches the database.
TENANT_SCHEMA = """
CREATE TABLE public.customers (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    tier text NOT NULL DEFAULT 'free'
);

-- RLS on, with a policy nothing anonymous satisfies. Phase 00 finding 7: the
-- anon grant is what makes this an empty set rather than 42501, and migrated
-- applications distinguish the two.
CREATE TABLE public.secrets (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value text NOT NULL
);
ALTER TABLE public.secrets ENABLE ROW LEVEL SECURITY;
CREATE POLICY owner_only ON public.secrets FOR SELECT TO authenticated
    USING (auth.uid() IS NOT NULL);
INSERT INTO public.secrets (value) VALUES ('should never be visible');

CREATE FUNCTION public.customer_count() RETURNS bigint
    LANGUAGE sql STABLE AS $$ SELECT count(*) FROM public.customers $$;

-- Phase 04 slice 3: per-user ownership, the shape a real application uses.
-- `owner_id` defaults to auth.uid() so a client never sends it, which is also
-- what makes the WITH CHECK meaningful -- a caller who *does* send someone
-- else's id must still be refused.
CREATE TABLE public.notes (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id uuid NOT NULL DEFAULT auth.uid(),
    body     text NOT NULL
);
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_select ON public.notes FOR SELECT TO authenticated
    USING (owner_id = auth.uid());
CREATE POLICY own_insert ON public.notes FOR INSERT TO authenticated
    WITH CHECK (owner_id = auth.uid());
"""


def _migrate_tenant_schema(tenant_conn) -> None:
    """Build `TENANT_SCHEMA` in a source database, then migrate it in.

    The source needs `auth.uid()` and the shared role names to exist before
    `pg_dump` will produce a dump referencing them -- which is exactly what a
    real Supabase project has. The `auth` schema itself is *not* carried:
    provisioning already built the destination's own, and slice 6b excludes
    Supabase's schemas for that reason.
    """
    import psycopg

    from services.migrate import data
    from services.migrate import schema as schema_tools
    from services.migrate import source as source_tools

    name = f"mldb_compat_src_{COMPAT_REF}"
    admin = psycopg.connect(ADMIN_DSN, autocommit=True)
    try:
        admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        admin.execute(f'CREATE DATABASE "{name}"')
        source_dsn = ADMIN_DSN.rsplit("/", 1)[0] + "/" + name

        with psycopg.connect(source_dsn, autocommit=True) as src:
            # The parts of a Supabase project this schema leans on. Roles are
            # cluster-wide, so they may already exist from a provisioned tenant.
            src.execute("CREATE SCHEMA IF NOT EXISTS auth")
            src.execute(
                "CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE "
                "AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$"
            )
            for role in ("anon", "authenticated", "service_role"):
                src.execute(
                    f"DO $$ BEGIN CREATE ROLE {role} NOLOGIN; "
                    "EXCEPTION WHEN duplicate_object THEN NULL; END $$"
                )
            src.execute(TENANT_SCHEMA)

        facts = source_tools.read(source_dsn)
        dumped = schema_tools.dump(source_dsn, ["public"])
        statements = schema_tools.statements_for(dumped, facts.functions.rows)
        for statement in statements:
            tenant_conn.execute(statement)
        tenant_conn.commit()

        # The rows too -- `secrets` is seeded by the schema and the suite reads
        # it back expecting an empty set rather than a 42501, which only means
        # anything if the row is actually there to be hidden.
        with psycopg.connect(source_dsn) as src:
            src.read_only = True
            data.prepare_source(src)
            # The same helper the CLI uses -- leaf relations only, so a
            # partitioned parent is not copied on top of its own partitions.
            tables = [
                table for table in data.copyable_tables(facts.relations.rows)
                if table.startswith("public.")
            ]
            copied = data.copy(src, tables, lambda sql: tenant_conn.execute(sql))
            tenant_conn.commit()
            for statement in data.sequence_statements(src, tables):
                tenant_conn.execute(statement)
            tenant_conn.commit()
        assert not copied.mismatches(), (
            f"the compat schema did not migrate cleanly: {copied.mismatches()}"
        )
    finally:
        admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        admin.close()


@pytest.fixture(scope="module")
def _module_db(migrated_database):
    """One tenant for the whole module, not one per test.

    Depends on `migrated_database` rather than opening its own pool so the
    schema is guaranteed present even when this file is the only one run.
    """
    from services.control_plane import db as database

    database.close_pool()
    database.init_pool(migrated_database)
    yield
    database.close_pool()


class _Mailbox(BaseHTTPRequestHandler):
    """Stands in for the platform's email hook.

    The suite now runs with confirmation **on**, which is the production posture
    (ADR-019). That needs somewhere for GoTrue's Send Email Hook to land and a
    way for the JavaScript suite to read the resulting link back.

    Deliberately not the real control-plane hook and not MaluMail: what is under
    test here is whether the official client copes with an unconfirmed user, and
    routing that through a third party would make an email outage look like a
    compatibility failure. The hook and MaluMail have their own tests, against
    the real thing, in tests/test_email_hook.py.
    """

    links: list = []

    def do_POST(self):
        payload = json.loads(self.rfile.read(int(self.headers.get("content-length", 0))))
        # Composed by the real function, so a change to link building shows up
        # here as a failed confirmation rather than passing unnoticed.
        _Mailbox.links.append(mail.verification_url(payload.get("email_data") or {}))
        self.send_response(200)
        self.send_header("content-type", "application/json")
        self.end_headers()
        self.wfile.write(b"{}")

    def do_GET(self):
        body = json.dumps({"link": _Mailbox.links[-1] if _Mailbox.links else None}).encode()
        self.send_response(200)
        self.send_header("content-type", "application/json")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


@pytest.fixture(scope="module")
def compat_stack(_module_db):
    """A provisioned tenant, a real PostgREST, a real GoTrue, and the gateway."""
    import uuid

    from services.control_plane import config as cp_config
    from services.control_plane import crypto, identity, provisioning
    from tests.conftest import TEST_CREDENTIAL, TEST_KEK

    key_ring = crypto.KeyRing(TEST_KEK)
    with db.connection() as conn:
        key_ring.load(conn)

    names = provisioning.TenantNames.for_ref(COMPAT_REF)
    with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
        admin.execute(f'DROP DATABASE IF EXISTS "{names.database}" WITH (FORCE)')
        for role in (names.authenticator, names.auth, names.admin):
            admin.execute(f'DROP ROLE IF EXISTS "{role}"')

    project_id = uuid.uuid4()
    with db.connection() as conn:
        # Children first: a previous run leaves keys and credentials behind,
        # and the foreign keys are there precisely to stop a project vanishing
        # while something still references it.
        for statement in (
            "DELETE FROM api_keys WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM project_credentials WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM provisioning_jobs WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM projects WHERE project_ref = %s",
        ):
            db.execute(conn, statement, (COMPAT_REF,))
        # Reused rather than recreated: the tenant is torn down between runs
        # but the platform account behind it need not be, and insisting on a
        # fresh one makes a re-run fail on leftovers from the last.
        existing = db.one(
            conn,
            "SELECT m.org_id FROM users u JOIN org_members m ON m.user_id = u.id "
            " WHERE u.email = %s LIMIT 1",
            (f"{COMPAT_REF}@example.com",),
        )
        if existing is None:
            _, org = identity.create_user_with_personal_org(
                conn, email=f"{COMPAT_REF}@example.com", password=TEST_CREDENTIAL
            )
        else:
            org = existing["org_id"]
        plan = db.one(
            conn,
            "INSERT INTO plans (code,name) VALUES ('compat','Compat') "
            "ON CONFLICT (code) DO UPDATE SET name='Compat' RETURNING id",
        )["id"]
        db.execute(
            conn,
            "INSERT INTO projects (id, org_id, project_ref, display_name, plan_id, status) "
            "VALUES (%s,%s,%s,%s,%s,'PLACEMENT_RESERVED')",
            (project_id, org, COMPAT_REF, "compat", plan),
        )
        conn.commit()

    admin_conn = psycopg.connect(ADMIN_DSN, row_factory=psycopg.rows.dict_row)
    _, passwords = _provision_core(project_id, admin_conn, key_ring, COMPAT_REF)

    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant_conn:
        tenant_conn.execute("CREATE EXTENSION IF NOT EXISTS maludb_core CASCADE")
        tenant_conn.commit()
        with db.connection() as conn:
            tenant_bootstrap.bootstrap_project(conn, tenant_conn, project_id=project_id)
        # **Migrated in, not executed in** (Phase 08 slice 8). The acceptance
        # criterion for the migration phase is the official client suite
        # passing against a project that *got there by migration*, so this
        # builds a Supabase-shaped source database, dumps it with `pg_dump`,
        # and restores it through the migration pipeline as
        # `mldb_<ref>_admin` -- the role the SQL route runs statements as.
        #
        # It is worth the trouble because this schema uses the two things a
        # migration is most likely to drop on the floor: a column defaulting to
        # `auth.uid()`, and policies granted `TO authenticated`. Both name
        # objects that belong to the *destination's* own bootstrap rather than
        # to the dump, so a migration that carried them wrongly, or resolved
        # them against the wrong `search_path`, produces a project whose tables
        # exist and whose row-level security does not work -- which is
        # precisely what this suite then measures.
        _migrate_tenant_schema(tenant_conn)
        tenant_conn.commit()

    settings = workers.WorkerSettings(
        project_ref=COMPAT_REF,
        database=names.database,
        authenticator_role=names.authenticator,
        authenticator_password=passwords["authenticator"],
        jwt_secret="compat-suite-jwt-secret-long-enough-for-hs256",  # noqa: S106
        port=POSTGREST_PORT,
    )
    config_dir = Path("/tmp/maludb-compat")  # noqa: S108 - test scratch, mode 0600 inside
    config_path = workers.write_config(settings, config_dir=config_dir)

    postgrest = subprocess.Popen(  # noqa: S603 - fixed binary, generated config
        [POSTGREST_BIN, str(config_path)], stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    workers.wait_until_ready(POSTGREST_PORT, timeout=30)

    # Created *after* PostgREST started, so the suite proves bootstrap 006's
    # reload rather than a lucky startup ordering.
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant_conn:
        tenant_conn.execute("CREATE TABLE public.late_table (id int)")
        tenant_conn.commit()

    # GoTrue, on the same signing secret PostgREST was configured with. A
    # different one would produce a project whose own Auth tokens its own Data
    # API rejects -- the failure the Phase 03 carry-forward note exists to warn
    # about, and one that looks like a compatibility bug rather than a config
    # mistake.
    auth_settings = auth_workers.AuthSettings(
        project_ref=COMPAT_REF,
        database=names.database,
        auth_role=names.auth,
        auth_password=passwords["auth"],
        jwt_secret=settings.jwt_secret,
        port=GOTRUE_PORT,
        site_url=f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}",
        external_url=f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}/auth/v1",
        # Confirmation on, which is the production posture ADR-019 requires.
        # The suite was on autoconfirm while slice 4 was outstanding; now that
        # the hook exists, running without it would leave the journey every real
        # user takes -- sign up, click, sign in -- untested through the official
        # client.
        autoconfirm=False,
        send_email_hook_uri=f"http://127.0.0.1:{MAILBOX_PORT}/hook",
        send_email_hook_secret=mail.generate_hook_secret(),
    )
    _Mailbox.links = []
    mailbox = HTTPServer(("127.0.0.1", MAILBOX_PORT), _Mailbox)
    threading.Thread(target=mailbox.serve_forever, daemon=True).start()

    auth_workers.migrate(auth_settings, binary=GOTRUE_BIN)
    auth_env = auth_workers.write_env(auth_settings, config_dir=config_dir)
    gotrue_env = dict(os.environ)
    for line in auth_env.read_text().splitlines():
        if line and not line.startswith("#"):
            key_name, _, raw = line.partition("=")
            gotrue_env[key_name] = raw.strip('"')
    gotrue = subprocess.Popen(  # noqa: S603 - fixed binary, generated environment
        [GOTRUE_BIN], env=gotrue_env, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    auth_workers.wait_until_ready(GOTRUE_PORT, timeout=30)

    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE projects SET status='ACTIVE', api_port=%s, worker_state='RUNNING', "
            "database_name=%s, auth_port=%s, auth_worker_state='RUNNING', auth_enabled=TRUE "
            "WHERE id = %s",
            (POSTGREST_PORT, names.database, GOTRUE_PORT, project_id),
        )
        issued = api_keys.create(
            conn,
            project_id=project_id,
            key_type=api_keys.PUBLISHABLE,
            pepper=TEST_PEPPER,
            key_ring=key_ring,
        )
        db.execute(
            conn,
            "UPDATE project_credentials SET revoked_at = now() "
            " WHERE project_id = %s AND credential_type = 'jwt_signing'",
            (project_id,),
        )
        conn.commit()
        # Store the same secret PostgREST was configured with, so a service_role
        # token the gateway mints verifies upstream.
        provisioning.store_credential(
            conn,
            project_id=project_id,
            credential_type="jwt_signing",
            role_name=None,
            secret=settings.jwt_secret,
            key_ring=key_ring,
        )
        conn.commit()

    gateway_config = cp_config.Config(
        environment="test",
        database_url=os.environ["MALUDB_CONTROL_PLANE_DATABASE_URL"],
        gateway_domain="maludb.local",
        docs_enabled=False,
        kek=TEST_KEK,
        token_pepper=TEST_PEPPER,
    )
    gateway = Gateway(config=gateway_config, key_ring=key_ring, wake_sleeping=False)
    server = uvicorn.Server(
        uvicorn.Config(create_app(gateway), host="127.0.0.1", port=GATEWAY_PORT, log_level="error")
    )
    threading.Thread(target=server.run, daemon=True).start()
    for _ in range(200):
        if server.started:
            break
        time.sleep(0.05)

    yield {
        "url": f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}",
        "key": issued.plaintext,
        "mailbox": f"http://127.0.0.1:{MAILBOX_PORT}/",
    }

    server.should_exit = True
    mailbox.shutdown()
    postgrest.terminate()
    postgrest.wait(timeout=10)
    gotrue.terminate()
    gotrue.wait(timeout=10)
    admin_conn.close()
    with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
        admin.execute(f'DROP DATABASE IF EXISTS "{names.database}" WITH (FORCE)')
        for role in (names.authenticator, names.auth, names.admin):
            admin.execute(f'DROP ROLE IF EXISTS "{role}"')
    shutil.rmtree(config_dir, ignore_errors=True)


@pytest.fixture(scope="module")
def compat_results(compat_stack):
    """Run the official client once; every test reads one case from the output."""
    completed = subprocess.run(  # noqa: S603 - fixed argv
        [shutil.which("node") or "node", str(COMPAT_DIR / "suite.mjs")],  # noqa: S607
        cwd=COMPAT_DIR,
        capture_output=True,
        text=True,
        timeout=180,
        env={**os.environ, "MALUDB_URL": compat_stack["url"], "MALUDB_KEY": compat_stack["key"],
             "MALUDB_MAILBOX": compat_stack["mailbox"]},
        check=False,
    )
    cases = {}
    for line in completed.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            row = json.loads(line)
            cases[row["name"]] = row
    if not cases:
        pytest.fail(f"the client suite produced no results.\nstdout:\n{completed.stdout}\n"
                    f"stderr:\n{completed.stderr}")
    return cases


# One test per behaviour rather than one for the whole suite: a single failing
# operation should name itself, and `specs/compatibility-matrix.yaml` is
# promoted per feature, so the evidence has to be per feature too.
@pytest.mark.parametrize(
    "case",
    [
        "select", "insert", "insert many", "update", "upsert", "filters",
        "ordering", "range and limit", "count", "rpc", "delete",
        "rls hides another tenant-scoped row",
        "a table created after the worker started is visible",
        "extension functions are not exposed as rpc",
        # Phase 04 slice 2. Driven through the same client and gateway, so what
        # is proven is that `supabase.auth` works against MaluDB rather than
        # that our reading of GoTrue's wire format is right.
        "auth signup",
        # The journey every real end user takes, and the part only the official
        # client can answer: what a migrated application sees before the link is
        # clicked. Phase 04's own end-to-end test drives GoTrue over raw HTTP,
        # so it cannot report how supabase-js surfaces an unconfirmed user.
        "an unconfirmed user cannot sign in",
        "following the confirmation link enables sign-in",
        "auth signin password",
        "auth token carries the claims RLS needs",
        "auth get user",
        "auth session refresh",
        "auth signout",
        "a wrong password is refused",
        # Phase 04 slice 3. Phase 03 could only claim RLS for anonymous
        # callers; these resolve auth.uid() from a GoTrue-issued token that
        # travelled through the gateway.
        "rls two signed-in users are distinguished",
        "rls refuses a row claimed for another user",
        "rls hides signed-in rows from an anonymous caller",
    ],
)
def test_official_client(compat_results, case):
    result = compat_results.get(case)
    assert result is not None, f"the client suite never ran {case!r}"
    assert result["ok"], f"{case}: {result.get('error')}"
