"""Migrating Auth users (Phase 08 slice 7, ADR-043).

The shape of this slice was decided by one measurement: **the console's role
cannot touch `auth.users`**. The tenant's `auth` schema is owned by
`mldb_<ref>_auth` (bootstrap 007) and the admin role holds only `USAGE` on the
schema, so `SELECT` and `INSERT` are both denied. Everything slices 6b and 6c do
-- compose SQL, send it to `POST /v1/projects/{ref}/sql` -- is unavailable here.

Granting the admin role access was the obvious alternative and was rejected:
it would put every end user's bcrypt hash within reach of anyone with console
access, on every tier, permanently, for a one-off operation. So the credential
stays platform-side behind a route that composes every statement itself.

That makes the tests here mostly about what the route *refuses*: SQL it is
sent, providers it will not carry, and columns nobody allowlisted.
"""

from __future__ import annotations

import uuid

import psycopg
import pytest

from services.control_plane.api import auth_import
from services.migrate import auth as auth_export
from tests.conftest import TEST_CREDENTIAL, requires_db
from tests.test_provisioning import ADMIN_DSN, _tenant_admin_dsn

pytestmark = [requires_db]
requires_node = pytest.mark.skipif(not ADMIN_DSN, reason="MALUDB_NODE_ADMIN_DSN is unset")


def _token(client, ref: str) -> str:
    return client.post(
        "/v1/auth/signin", json={"email": f"{ref}@example.com", "password": TEST_CREDENTIAL}
    ).json()["token"]


def _allow_several_statements(ref: str) -> None:
    """Free resolves one console statement per eight-second window, and a test
    that sends two gets a 429 that looks like the thing under test failing."""
    from services.control_plane import db

    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE plans SET config_json = %s WHERE id = "
            "  (SELECT plan_id FROM projects WHERE project_ref = %s)",
            (psycopg.types.json.Jsonb({"limits": {"sql_console_concurrent": 20}}), ref),
        )
        conn.commit()


def _auth_schema(dsn: str, database: str) -> None:
    """A GoTrue-shaped auth schema, created the way a real one is.

    `SET ROLE` to the tenant's auth role first, because that is who owns these
    tables in production: bootstrap 007 hands the schema to `mldb_<ref>_auth`
    and GoTrue migrates as that role. Created as the platform superuser instead,
    the import route -- which connects *as* the auth role -- is denied its own
    tables, which is a fixture bug that looks exactly like a permissions bug.
    """
    with psycopg.connect(dsn, autocommit=True) as conn:
        conn.execute(f'SET ROLE "{database}_auth"')
        # No `CREATE SCHEMA`: bootstrap 002 made it and 007 handed it to this
        # role, and `IF NOT EXISTS` still checks CREATE on the database first.
        conn.execute("""
            CREATE TABLE IF NOT EXISTS auth.users (
                id uuid PRIMARY KEY,
                aud varchar(255), role varchar(255), email varchar(255),
                encrypted_password varchar(255),
                email_confirmed_at timestamptz, last_sign_in_at timestamptz,
                raw_app_meta_data jsonb, raw_user_meta_data jsonb,
                created_at timestamptz, updated_at timestamptz,
                phone text, phone_confirmed_at timestamptz,
                is_super_admin boolean, deleted_at timestamptz
            );
            CREATE TABLE IF NOT EXISTS auth.identities (
                id uuid PRIMARY KEY,
                user_id uuid REFERENCES auth.users(id),
                provider text NOT NULL, provider_id text,
                identity_data jsonb,
                last_sign_in_at timestamptz, created_at timestamptz, updated_at timestamptz
            );
        """)


# -- the allowlist, which needs no database --------------------------------


def test_the_columns_that_are_deliberately_not_carried():
    """In-flight secrets belong to the platform they were minted on.

    Carrying `confirmation_token` or `recovery_token` across a cutover would let
    a token Supabase issued be redeemed against MaluDB. A user midway through a
    password reset starts it again, which is the correct outcome.
    """
    for column in (
        "confirmation_token", "recovery_token", "email_change_token_new",
        "email_change_token_current", "reauthentication_token",
    ):
        assert column not in auth_import.USER_COLUMNS
        assert column not in auth_export.USER_COLUMNS

    # Not a customer's to set, and not the source's to carry.
    assert "is_super_admin" not in auth_import.USER_COLUMNS
    # Generated by newer GoTrue, which refuses to be told a value.
    assert "confirmed_at" not in auth_import.USER_COLUMNS
    # Legacy, always zero.
    assert "instance_id" not in auth_import.USER_COLUMNS


def test_only_email_identities_are_accepted():
    """ADR-043. The scanner reports an external identity as a blocker; this is
    the same rule where it cannot be skipped."""
    assert auth_import.ALLOWED_PROVIDERS == frozenset({"email"})


def test_a_column_nobody_allowlisted_is_dropped_rather_than_written():
    """The route decides what may be written, not the caller."""
    kept, dropped = auth_import._rows_for(
        [{"id": "x", "email": "a@b.c", "is_super_admin": True, "banned_until": "3000-01-01"}],
        auth_import.USER_COLUMNS,
        {"id", "email", "is_super_admin", "banned_until"},
    )
    assert kept == [{"id": "x", "email": "a@b.c"}]
    assert dropped == {"is_super_admin", "banned_until"}


def test_a_column_this_platforms_gotrue_lacks_is_named(capsys):  # noqa: ARG001
    """Supabase and this platform pin different GoTrue versions, so a column in
    the source may not exist here. Named rather than silently discarded."""
    kept, dropped = auth_import._rows_for(
        [{"id": "x", "phone": "+100", "email": "a@b.c"}],
        auth_import.USER_COLUMNS,
        {"id", "email"},  # this destination has no `phone`
    )
    assert kept == [{"id": "x", "email": "a@b.c"}]
    assert dropped == {"phone"}


# -- against a real tenant -------------------------------------------------


@requires_node
def test_the_consoles_role_cannot_reach_auth_users(client, tenant):
    """The measurement this slice is built on, kept as a test.

    If this ever starts failing, the reason `api/auth_import.py` exists has
    changed and the decision to keep the auth credential platform-side should be
    revisited rather than the test deleted.
    """
    ref = "auth0001"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")
    _allow_several_statements(ref)

    token = _token(client, ref)
    for statement in (
        "SELECT count(*) FROM auth.users",
        "INSERT INTO auth.users (id, email) VALUES (gen_random_uuid(), 'x@y.z')",
    ):
        answered = client.post(
            f"/v1/projects/{ref}/sql", json={"statement": statement},
            headers={"Authorization": f"Bearer {token}"},
        )
        assert answered.status_code == 400
        assert "permission denied" in answered.json()["detail"]


@requires_node
def test_users_and_their_password_hashes_arrive(client, tenant):
    """The point of migrating auth at all: a user signs in with the password
    they already had, rather than discovering at cutover that they must reset."""
    ref = "auth0002"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    user_id = str(uuid.uuid4())
    bcrypt_hash = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"  # noqa: S105
    payload = {
        "users": [{
            "id": user_id, "aud": "authenticated", "role": "authenticated",
            "email": "person@example.com", "encrypted_password": bcrypt_hash,
            "email_confirmed_at": "2024-01-01T00:00:00+00:00",
            "raw_user_meta_data": {"name": "A Person"},
            "created_at": "2024-01-01T00:00:00+00:00",
        }],
        "identities": [],
    }

    answered = client.post(
        f"/v1/projects/{ref}/auth/import", json=payload,
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 200, answered.text
    assert answered.json()["users_inserted"] == 1

    with psycopg.connect(_tenant_admin_dsn(f"mldb_{ref}")) as conn, conn.cursor() as cur:
        cur.execute("SELECT email, encrypted_password, raw_user_meta_data FROM auth.users")
        email, stored_hash, meta = cur.fetchone()
    assert email == "person@example.com"
    assert stored_hash == bcrypt_hash, "the password hash did not survive the import"
    assert meta == {"name": "A Person"}


@requires_node
def test_a_second_import_is_a_no_op_rather_than_a_duplicate_key(client, tenant):
    """A migration retried after a network failure must not fail mid-cutover."""
    ref = "auth0003"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")
    headers = {"Authorization": f"Bearer {_token(client, ref)}"}
    payload = {"users": [{"id": str(uuid.uuid4()), "email": "again@example.com"}]}

    first = client.post(f"/v1/projects/{ref}/auth/import", json=payload, headers=headers)
    second = client.post(f"/v1/projects/{ref}/auth/import", json=payload, headers=headers)

    assert first.json()["users_inserted"] == 1
    assert second.status_code == 200
    assert second.json()["users_inserted"] == 0
    assert second.json()["users_skipped"] == 1


@requires_node
def test_the_route_refuses_a_provider_it_does_not_migrate(client, tenant):
    """ADR-043, enforced where a customer cannot skip it by not running the
    scanner."""
    ref = "auth0004"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"identities": [{"id": str(uuid.uuid4()), "provider": "google"}]},
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 400
    assert "google" in answered.json()["detail"]


@requires_node
def test_a_caller_cannot_set_is_super_admin(client, tenant):
    """The route composes from an allowlist, so a value nobody allowlisted is
    not written -- and the answer says it was dropped."""
    ref = "auth0005"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"users": [{
            "id": str(uuid.uuid4()), "email": "sneaky@example.com", "is_super_admin": True,
        }]},
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 200
    assert "is_super_admin" in answered.json()["dropped_columns"]

    with psycopg.connect(_tenant_admin_dsn(f"mldb_{ref}")) as conn, conn.cursor() as cur:
        cur.execute("SELECT is_super_admin FROM auth.users WHERE email = 'sneaky@example.com'")
        assert cur.fetchone()[0] is None


@requires_node
def test_a_caller_cannot_choose_the_database_role_their_token_maps_to(client, tenant):
    """The escalation the slice 7 security review found, and the worst bug in
    this phase.

    `auth.users.role` is not application data. GoTrue copies it into the `role`
    claim of every token it mints; PostgREST has no `jwt-role-claim-key`
    override so it reads that claim and issues `SET LOCAL ROLE`; and
    `service_role` is created `BYPASSRLS` with `ALL` on every table in `public`.
    Allowlisting the column let a caller choose the database role their token
    would map to -- and with a password they picked, the account signs in over
    the public gateway and reads the whole tenant past RLS.

    Worse than "a member already has access": a member's `service_role` API key
    is revoked by key rotation at offboarding. A password-authenticated account
    is not, and it is invisible in the key inventory.
    """
    ref = "auth0007"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"users": [{
            "id": str(uuid.uuid4()),
            "email": "backdoor@example.com",
            "encrypted_password": "$2a$10$" + "x" * 22,  # noqa: S106
            "email_confirmed_at": "2024-01-01T00:00:00+00:00",
            "role": "service_role",
            "aud": "authenticated",
        }]},
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 200, answered.text

    with psycopg.connect(_tenant_admin_dsn(f"mldb_{ref}")) as conn, conn.cursor() as cur:
        cur.execute("SELECT role, aud FROM auth.users WHERE email = 'backdoor@example.com'")
        role, aud = cur.fetchone()
    assert role == "authenticated", f"a caller chose the database role: {role}"
    assert aud == "authenticated"

    # And the column is not on the allowlist at all, so it cannot come back by
    # someone adding a value check instead.
    assert "role" not in auth_import.USER_COLUMNS
    assert "aud" not in auth_import.USER_COLUMNS


@requires_node
def test_a_failed_import_leaves_nothing_written_and_is_still_audited(client, tenant):
    """Reproduced during the review: users committed, identities failed, the
    caller got a 400, and `audit_events` recorded nothing -- on the one route
    holding the tenant's auth credential."""
    from services.control_plane import db

    ref = "auth0008"
    project_id, _, _ = tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={
            "users": [{"id": str(uuid.uuid4()), "email": "planted@example.com"}],
            # A user_id that does not exist: the foreign key cannot resolve.
            "identities": [{
                "id": str(uuid.uuid4()), "user_id": str(uuid.uuid4()),
                "provider": "email", "provider_id": "planted@example.com",
                "identity_data": {"sub": "x"},
            }],
        },
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 400

    with psycopg.connect(_tenant_admin_dsn(f"mldb_{ref}")) as conn, conn.cursor() as cur:
        cur.execute("SELECT count(*) FROM auth.users WHERE email = 'planted@example.com'")
        assert cur.fetchone()[0] == 0, "a failed import left a user committed"

    with db.connection() as conn:
        row = db.one(
            conn,
            "SELECT count(*) AS n FROM audit_events "
            " WHERE project_id = %s AND event_type = 'project.auth.import_failed'",
            (project_id,),
        )
    assert row["n"] == 1, "a failed import left no trace that the route ran"


@requires_node
def test_importing_users_is_a_manager_action(client, tenant, db_pool):  # noqa: ARG001
    """More consequential than running a statement: it writes the principals
    tokens are minted for. An ordinary member gets the console; this needs
    owner or admin."""
    from services.control_plane import db, identity

    ref = "auth0009"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    # A plain member of the same organization.
    with db.connection() as conn:
        org = db.one(
            conn, "SELECT org_id FROM projects WHERE project_ref = %s", (ref,)
        )["org_id"]
        member, _ = identity.create_user_with_personal_org(
            conn, email=f"member-{ref}@example.com", password=TEST_CREDENTIAL
        )
        db.execute(
            conn,
            "INSERT INTO org_members (org_id, user_id, role) VALUES (%s, %s, 'member')",
            (org, member.id),
        )
        conn.commit()

    token = client.post(
        "/v1/auth/signin",
        json={"email": f"member-{ref}@example.com", "password": TEST_CREDENTIAL},
    ).json()["token"]

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"users": [{"id": str(uuid.uuid4()), "email": "nope@example.com"}]},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert answered.status_code == 403


@requires_node
def test_authorization_metadata_is_carried_but_counted(client, tenant):
    """`raw_app_meta_data` becomes GoTrue's `app_metadata` claim, and
    Supabase-shaped policies commonly read `role` out of it.

    Carried rather than stripped -- it is the customer's own data and their
    policies already trusted it on Supabase -- but counted, because importing it
    is an authorization decision rather than a copy.
    """
    ref = "auth0010"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"users": [{
            "id": str(uuid.uuid4()), "email": "claims@example.com",
            "raw_app_meta_data": {"provider": "email", "role": "admin"},
        }]},
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 200
    assert answered.json()["users_with_claim_metadata"] == 1


@requires_node
def test_a_value_that_looks_like_sql_is_a_value(client, tenant):
    """The route takes JSON and composes the statement itself, so nothing a
    caller sends is executed. The privileged connection is only safe because of
    this."""
    ref = "auth0006"
    tenant(ref)
    _auth_schema(_tenant_admin_dsn(f"mldb_{ref}"), f"mldb_{ref}")

    hostile = "x'); DROP TABLE auth.users; --"
    answered = client.post(
        f"/v1/projects/{ref}/auth/import",
        json={"users": [{"id": str(uuid.uuid4()), "email": hostile}]},
        headers={"Authorization": f"Bearer {_token(client, ref)}"},
    )
    assert answered.status_code == 200

    with psycopg.connect(_tenant_admin_dsn(f"mldb_{ref}")) as conn, conn.cursor() as cur:
        cur.execute("SELECT email FROM auth.users")
        assert cur.fetchone()[0] == hostile, "the value was not stored verbatim"


@requires_node
def test_a_project_you_do_not_belong_to_is_not_found(client, db_pool):  # noqa: ARG001
    """Same gates as every other tenant route, including the uniform 404."""
    client.post("/v1/auth/signup",
                json={"email": "authoutsider@example.com", "password": TEST_CREDENTIAL})
    token = client.post(
        "/v1/auth/signin",
        json={"email": "authoutsider@example.com", "password": TEST_CREDENTIAL},
    ).json()["token"]

    answered = client.post(
        "/v1/projects/somebodyelse/auth/import", json={"users": []},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert answered.status_code == 404
    assert answered.json()["detail"] == "project not found"


def test_an_unauthenticated_caller_is_refused(client, db_pool):  # noqa: ARG001
    assert client.post("/v1/projects/anyref/auth/import", json={"users": []}).status_code == 401
