"""Phase 03's proof milestone, run with the official Supabase client.

    const client = createClient('https://<ref>.maludb.com', '<publishable-key>')
    const { data, error } = await client.from('customers').select('*')

Everything in the path is real: a tenant provisioned by Phase 02 code, hardened
by its bootstrap, served by PostgREST 14.17, reached through the Phase 03
gateway over a hostname that actually resolves, authenticated with a key issued
by slice 1.

Reimplementing the client in Python would test our reading of its behaviour
rather than the behaviour. Phase 00 found three incompatibilities that only
appeared with the real client in the loop -- `GENERATED ALWAYS` breaking
`.upsert()`, the schema cache hiding new tables, and extension functions
appearing as RPC -- and each is asserted here as a regression test.
"""

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import psycopg
import pytest
import uvicorn

from services.control_plane import api_keys, auth_workers, db, mail, tenant_bootstrap, workers
from services.gateway.app import Gateway, create_app
from tests.conftest import TEST_PEPPER, requires_db
from tests.test_provisioning import (
    ADMIN_DSN,
    _provision_core,
    _tenant_admin_dsn,
    requires_maludb_core,
)

# Fixed so the hosts entry is stable and can be made once during environment
# setup rather than mutated per test run.
COMPAT_REF = "cmpt0001"
GATEWAY_PORT = 28110
POSTGREST_PORT = 28432
GOTRUE_PORT = 28433
MAILBOX_PORT = 28434

COMPAT_DIR = Path(__file__).parent / "compat"
POSTGREST_BIN = os.environ.get("MALUDB_POSTGREST_BIN", "postgrest")
GOTRUE_BIN = os.environ.get("MALUDB_GOTRUE_BIN", "gotrue")


def _resolves(hostname: str) -> bool:
    try:
        socket.getaddrinfo(hostname, None)
    except socket.gaierror:
        return False
    return True


requires_node = pytest.mark.skipif(shutil.which("node") is None, reason="node is not installed")
requires_client = pytest.mark.skipif(
    not (COMPAT_DIR / "node_modules").exists(),
    reason="run `npm install` in tests/compat",
)
requires_postgrest = pytest.mark.skipif(
    shutil.which(POSTGREST_BIN) is None and not os.path.exists(POSTGREST_BIN),
    reason="PostgREST binary not available",
)
requires_hostname = pytest.mark.skipif(
    not _resolves(f"{COMPAT_REF}.maludb.local"),
    reason=f"add '127.0.0.1 {COMPAT_REF}.maludb.local' to /etc/hosts",
)

pytestmark = [
    requires_db,
    pytest.mark.skipif(not ADMIN_DSN, reason="MALUDB_NODE_ADMIN_DSN is unset"),
    requires_maludb_core,
    requires_postgrest,
    requires_node,
    requires_client,
    requires_hostname,
]


# The schema a customer would arrive with. Created as the tenant admin, which
# is how a dashboard SQL editor or a migration tool reaches the database.
TENANT_SCHEMA = """
CREATE TABLE public.customers (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    tier text NOT NULL DEFAULT 'free'
);

-- RLS on, with a policy nothing anonymous satisfies. Phase 00 finding 7: the
-- anon grant is what makes this an empty set rather than 42501, and migrated
-- applications distinguish the two.
CREATE TABLE public.secrets (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value text NOT NULL
);
ALTER TABLE public.secrets ENABLE ROW LEVEL SECURITY;
CREATE POLICY owner_only ON public.secrets FOR SELECT TO authenticated
    USING (auth.uid() IS NOT NULL);
INSERT INTO public.secrets (value) VALUES ('should never be visible');

CREATE FUNCTION public.customer_count() RETURNS bigint
    LANGUAGE sql STABLE AS $$ SELECT count(*) FROM public.customers $$;

-- Phase 04 slice 3: per-user ownership, the shape a real application uses.
-- `owner_id` defaults to auth.uid() so a client never sends it, which is also
-- what makes the WITH CHECK meaningful -- a caller who *does* send someone
-- else's id must still be refused.
CREATE TABLE public.notes (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id uuid NOT NULL DEFAULT auth.uid(),
    body     text NOT NULL
);
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_select ON public.notes FOR SELECT TO authenticated
    USING (owner_id = auth.uid());
CREATE POLICY own_insert ON public.notes FOR INSERT TO authenticated
    WITH CHECK (owner_id = auth.uid());

-- ADR-076: the Supabase patterns that fail when customer roles cannot execute
-- extension functions, migrated in like everything above. `EXECUTE` is checked
-- against whoever runs the statement -- column defaults and trigger bodies
-- included -- so each of these is exercised as `anon` or a signed-in user by the
-- suite, never as the superuser that builds it.
CREATE TABLE public.documents (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    body        text NOT NULL,
    secret_hash text,
    embedding   vector(3) NOT NULL
);
CREATE FUNCTION public.hash_document_secret() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.secret_hash IS NOT NULL THEN
        NEW.secret_hash := crypt(NEW.secret_hash, gen_salt('bf', 4));
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER hash_document_secret BEFORE INSERT ON public.documents
    FOR EACH ROW EXECUTE FUNCTION public.hash_document_secret();
INSERT INTO public.documents (body, embedding)
    VALUES ('north', '[1,0,0]'), ('east', '[0,1,0]'), ('up', '[0,0,1]');

-- The shape Supabase's own pgvector guide gives, called over RPC.
CREATE FUNCTION public.match_documents(query_embedding vector(3), match_count int)
RETURNS TABLE (body text, distance double precision)
LANGUAGE sql STABLE AS $$
    SELECT body, embedding <=> query_embedding
      FROM public.documents
     ORDER BY embedding <=> query_embedding
     LIMIT match_count
$$;
"""

# The customer's own functions in TENANT_SCHEMA. Every other RPC path the Data API
# describes belongs to an extension, and each must be refused (ADR-076 decision 3).
TENANT_RPC = ("customer_count", "match_documents")


def _migrate_tenant_schema(tenant_conn) -> None:
    """Build `TENANT_SCHEMA` in a source database, then migrate it in.

    The source needs `auth.uid()` and the shared role names to exist before
    `pg_dump` will produce a dump referencing them -- which is exactly what a
    real Supabase project has. The `auth` schema itself is *not* carried:
    provisioning already built the destination's own, and slice 6b excludes
    Supabase's schemas for that reason.
    """
    import psycopg

    from services.migrate import data
    from services.migrate import schema as schema_tools
    from services.migrate import source as source_tools

    name = f"mldb_compat_src_{COMPAT_REF}"
    admin = psycopg.connect(ADMIN_DSN, autocommit=True)
    try:
        admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        admin.execute(f'CREATE DATABASE "{name}"')
        source_dsn = ADMIN_DSN.rsplit("/", 1)[0] + "/" + name

        with psycopg.connect(source_dsn, autocommit=True) as src:
            # The parts of a Supabase project this schema leans on. Roles are
            # cluster-wide, so they may already exist from a provisioned tenant.
            src.execute("CREATE SCHEMA IF NOT EXISTS auth")
            src.execute(
                "CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE "
                "AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$"
            )
            for role in ("anon", "authenticated", "service_role"):
                src.execute(
                    f"DO $$ BEGIN CREATE ROLE {role} NOLOGIN; "
                    "EXCEPTION WHEN duplicate_object THEN NULL; END $$"
                )
            for extension in ("vector", "pgcrypto", "uuid-ossp"):
                src.execute(f'CREATE EXTENSION IF NOT EXISTS "{extension}"')
            src.execute(TENANT_SCHEMA)

        # Extensions are database-level and the migration applies them before
        # the schema (services/migrate/destination.py). vector and pgcrypto are
        # already here through maludb_core; uuid-ossp is the one a Supabase
        # schema brings, installed so ADR-076's event trigger grants it.
        tenant_conn.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
        tenant_conn.commit()

        facts = source_tools.read(source_dsn)
        dumped = schema_tools.dump(source_dsn, ["public"])
        statements = schema_tools.statements_for(dumped, facts.functions.rows)
        for statement in statements:
            tenant_conn.execute(statement)
        tenant_conn.commit()

        # The rows too -- `secrets` is seeded by the schema and the suite reads
        # it back expecting an empty set rather than a 42501, which only means
        # anything if the row is actually there to be hidden.
        with psycopg.connect(source_dsn) as src:
            src.read_only = True
            data.prepare_source(src)
            # The same helper the CLI uses -- leaf relations only, so a
            # partitioned parent is not copied on top of its own partitions.
            tables = [
                table for table in data.copyable_tables(facts.relations.rows)
                if table.startswith("public.")
            ]
            copied = data.copy(src, tables, lambda sql: tenant_conn.execute(sql))
            tenant_conn.commit()
            for statement in data.sequence_statements(src, tables):
                tenant_conn.execute(statement)
            tenant_conn.commit()
        assert not copied.mismatches(), (
            f"the compat schema did not migrate cleanly: {copied.mismatches()}"
        )
    finally:
        admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        admin.close()


@pytest.fixture(scope="module")
def _module_db(migrated_database):
    """One tenant for the whole module, not one per test.

    Depends on `migrated_database` rather than opening its own pool so the
    schema is guaranteed present even when this file is the only one run.
    """
    from services.control_plane import db as database

    database.close_pool()
    database.init_pool(migrated_database)
    yield
    database.close_pool()


class _Mailbox(BaseHTTPRequestHandler):
    """Stands in for the platform's email hook.

    The suite now runs with confirmation **on**, which is the production posture
    (ADR-019). That needs somewhere for GoTrue's Send Email Hook to land and a
    way for the JavaScript suite to read the resulting link back.

    Deliberately not the real control-plane hook and not MaluMail: what is under
    test here is whether the official client copes with an unconfirmed user, and
    routing that through a third party would make an email outage look like a
    compatibility failure. The hook and MaluMail have their own tests, against
    the real thing, in tests/test_email_hook.py.
    """

    links: list = []

    def do_POST(self):
        payload = json.loads(self.rfile.read(int(self.headers.get("content-length", 0))))
        # Composed by the real function, so a change to link building shows up
        # here as a failed confirmation rather than passing unnoticed.
        _Mailbox.links.append(mail.verification_url(payload.get("email_data") or {}))
        self.send_response(200)
        self.send_header("content-type", "application/json")
        self.end_headers()
        self.wfile.write(b"{}")

    def do_GET(self):
        body = json.dumps({"link": _Mailbox.links[-1] if _Mailbox.links else None}).encode()
        self.send_response(200)
        self.send_header("content-type", "application/json")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


def _started_or_fail(process, port: int, what: str, ready) -> None:
    """Wait for readiness, and refuse to accept somebody else's process.

    `wait_until_ready` is given a port and nothing else, which is right for the
    control plane -- it is asking whether the surface answers, not who is behind
    it. In a test fixture that is not enough. A worker left running by an earlier
    interrupted run holds the port, this run's process dies with
    `bind: resource busy`, readiness passes against the orphan, and every case
    then fails against a tenant database that has since been dropped: 16 red
    tests naming `select`, `insert`, `rls ...` and nothing naming the port.

    That is the same shape as the stale `weed` server slice 3 found and the
    negative cases slice 5 found passing against a dead endpoint. The fix is the
    same one: assert something only the process you started can satisfy.
    """
    try:
        ready(port, timeout=30)
    except Exception:
        if process.poll() is not None:
            raise AssertionError(
                f"{what} exited with {process.returncode} instead of starting; "
                f"see the log beside this fixture. A previous run's {what} still "
                f"holding port {port} is the usual cause."
            ) from None
        raise
    if process.poll() is not None:
        raise AssertionError(
            f"{what} answered on port {port} but this run's process had already exited "
            f"with {process.returncode} -- the port is held by something else, most "
            f"likely a {what} left behind by an interrupted run. Kill it and re-run; "
            "every case would otherwise fail against the wrong database."
        )


@pytest.fixture(scope="module")
def compat_stack(_module_db):
    """A provisioned tenant, a real PostgREST, a real GoTrue, and the gateway."""
    import uuid

    from services.control_plane import config as cp_config
    from services.control_plane import crypto, identity, provisioning
    from tests.conftest import TEST_CREDENTIAL, TEST_KEK

    key_ring = crypto.KeyRing(TEST_KEK)
    with db.connection() as conn:
        key_ring.load(conn)

    names = provisioning.TenantNames.for_ref(COMPAT_REF)
    with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
        admin.execute(f'DROP DATABASE IF EXISTS "{names.database}" WITH (FORCE)')
        for role in (names.authenticator, names.auth, names.admin):
            admin.execute(f'DROP ROLE IF EXISTS "{role}"')

    project_id = uuid.uuid4()
    with db.connection() as conn:
        # Children first: a previous run leaves keys and credentials behind,
        # and the foreign keys are there precisely to stop a project vanishing
        # while something still references it.
        for statement in (
            "DELETE FROM api_keys WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM project_credentials WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM provisioning_jobs WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            # Phase 12 slice 5: enabling the data-model graph records an audit
            # event, and `audit_events` does not cascade -- so without this a
            # second local run cannot set the stack up at all.
            "DELETE FROM audit_events WHERE project_id IN "
            "(SELECT id FROM projects WHERE project_ref = %s)",
            "DELETE FROM projects WHERE project_ref = %s",
        ):
            db.execute(conn, statement, (COMPAT_REF,))
        # Reused rather than recreated: the tenant is torn down between runs
        # but the platform account behind it need not be, and insisting on a
        # fresh one makes a re-run fail on leftovers from the last.
        existing = db.one(
            conn,
            "SELECT m.org_id FROM users u JOIN org_members m ON m.user_id = u.id "
            " WHERE u.email = %s LIMIT 1",
            (f"{COMPAT_REF}@example.com",),
        )
        if existing is None:
            _, org = identity.create_user_with_personal_org(
                conn, email=f"{COMPAT_REF}@example.com", password=TEST_CREDENTIAL
            )
        else:
            org = existing["org_id"]
        plan = db.one(
            conn,
            "INSERT INTO plans (code,name) VALUES ('compat','Compat') "
            "ON CONFLICT (code) DO UPDATE SET name='Compat' RETURNING id",
        )["id"]
        db.execute(
            conn,
            "INSERT INTO projects (id, org_id, project_ref, display_name, plan_id, status) "
            "VALUES (%s,%s,%s,%s,%s,'PLACEMENT_RESERVED')",
            (project_id, org, COMPAT_REF, "compat", plan),
        )
        conn.commit()

    admin_conn = psycopg.connect(ADMIN_DSN, row_factory=psycopg.rows.dict_row)
    _, passwords = _provision_core(project_id, admin_conn, key_ring, COMPAT_REF)

    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant_conn:
        tenant_conn.execute("CREATE EXTENSION IF NOT EXISTS maludb_core CASCADE")
        tenant_conn.commit()
        with db.connection() as conn:
            # Live: PostgREST is started below with the check named, and not
            # before -- the provisioning pipeline's own ordering (ADR-076).
            tenant_bootstrap.bootstrap_project(
                conn, tenant_conn, project_id=project_id, rpc_check_live=True
            )
        # **Migrated in, not executed in** (Phase 08 slice 8). The acceptance
        # criterion for the migration phase is the official client suite
        # passing against a project that *got there by migration*, so this
        # builds a Supabase-shaped source database, dumps it with `pg_dump`,
        # and restores it through the migration pipeline as
        # `mldb_<ref>_admin` -- the role the SQL route runs statements as.
        #
        # It is worth the trouble because this schema uses the two things a
        # migration is most likely to drop on the floor: a column defaulting to
        # `auth.uid()`, and policies granted `TO authenticated`. Both name
        # objects that belong to the *destination's* own bootstrap rather than
        # to the dump, so a migration that carried them wrongly, or resolved
        # them against the wrong `search_path`, produces a project whose tables
        # exist and whose row-level security does not work -- which is
        # precisely what this suite then measures.
        _migrate_tenant_schema(tenant_conn)
        tenant_conn.commit()

    settings = workers.WorkerSettings(
        project_ref=COMPAT_REF,
        database=names.database,
        authenticator_role=names.authenticator,
        authenticator_password=passwords["authenticator"],
        jwt_secret="compat-suite-jwt-secret-long-enough-for-hs256",  # noqa: S106
        port=POSTGREST_PORT,
        pre_request=workers.pre_request_for(tenant_bootstrap.latest_version()),
    )
    config_dir = Path("/tmp/maludb-compat")  # noqa: S108 - test scratch, mode 0600 inside
    config_path = workers.write_config(settings, config_dir=config_dir)

    postgrest = subprocess.Popen(  # noqa: S603 - fixed binary, generated config
        [POSTGREST_BIN, str(config_path)], stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    _started_or_fail(postgrest, POSTGREST_PORT, "PostgREST", workers.wait_until_ready)

    # Created *after* PostgREST started, so the suite proves bootstrap 006's
    # reload rather than a lucky startup ordering.
    with psycopg.connect(_tenant_admin_dsn(names.database)) as tenant_conn:
        tenant_conn.execute("CREATE TABLE public.late_table (id int)")
        tenant_conn.commit()

    # GoTrue, on the same signing secret PostgREST was configured with. A
    # different one would produce a project whose own Auth tokens its own Data
    # API rejects -- the failure the Phase 03 carry-forward note exists to warn
    # about, and one that looks like a compatibility bug rather than a config
    # mistake.
    auth_settings = auth_workers.AuthSettings(
        project_ref=COMPAT_REF,
        database=names.database,
        auth_role=names.auth,
        auth_password=passwords["auth"],
        jwt_secret=settings.jwt_secret,
        port=GOTRUE_PORT,
        site_url=f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}",
        external_url=f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}/auth/v1",
        # Confirmation on, which is the production posture ADR-019 requires.
        # The suite was on autoconfirm while slice 4 was outstanding; now that
        # the hook exists, running without it would leave the journey every real
        # user takes -- sign up, click, sign in -- untested through the official
        # client.
        autoconfirm=False,
        send_email_hook_uri=f"http://127.0.0.1:{MAILBOX_PORT}/hook",
        send_email_hook_secret=mail.generate_hook_secret(),
    )
    _Mailbox.links = []
    mailbox = HTTPServer(("127.0.0.1", MAILBOX_PORT), _Mailbox)
    threading.Thread(target=mailbox.serve_forever, daemon=True).start()

    auth_workers.migrate(auth_settings, binary=GOTRUE_BIN)
    auth_env = auth_workers.write_env(auth_settings, config_dir=config_dir)
    gotrue_env = dict(os.environ)
    for line in auth_env.read_text().splitlines():
        if line and not line.startswith("#"):
            key_name, _, raw = line.partition("=")
            gotrue_env[key_name] = raw.strip('"')
    gotrue = subprocess.Popen(  # noqa: S603 - fixed binary, generated environment
        [GOTRUE_BIN], env=gotrue_env, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    _started_or_fail(gotrue, GOTRUE_PORT, "GoTrue", auth_workers.wait_until_ready)

    with db.connection() as conn:
        db.execute(
            conn,
            "UPDATE projects SET status='ACTIVE', api_port=%s, worker_state='RUNNING', "
            "database_name=%s, auth_port=%s, auth_worker_state='RUNNING', auth_enabled=TRUE "
            "WHERE id = %s",
            (POSTGREST_PORT, names.database, GOTRUE_PORT, project_id),
        )
        issued = api_keys.create(
            conn,
            project_id=project_id,
            key_type=api_keys.PUBLISHABLE,
            pepper=TEST_PEPPER,
            key_ring=key_ring,
        )
        db.execute(
            conn,
            "UPDATE project_credentials SET revoked_at = now() "
            " WHERE project_id = %s AND credential_type = 'jwt_signing'",
            (project_id,),
        )
        conn.commit()
        # Store the same secret PostgREST was configured with, so a service_role
        # token the gateway mints verifies upstream.
        provisioning.store_credential(
            conn,
            project_id=project_id,
            credential_type="jwt_signing",
            role_name=None,
            secret=settings.jwt_secret,
            key_ring=key_ring,
        )
        conn.commit()

    gateway_config = cp_config.Config(
        environment="test",
        database_url=os.environ["MALUDB_CONTROL_PLANE_DATABASE_URL"],
        gateway_domain="maludb.local",
        database_domain="db.maludb.local",
        docs_enabled=False,
        kek=TEST_KEK,
        token_pepper=TEST_PEPPER,
    )
    gateway = Gateway(config=gateway_config, key_ring=key_ring, wake_sleeping=False)
    server = uvicorn.Server(
        uvicorn.Config(create_app(gateway), host="127.0.0.1", port=GATEWAY_PORT, log_level="error")
    )
    threading.Thread(target=server.run, daemon=True).start()
    for _ in range(200):
        if server.started:
            break
        time.sleep(0.05)

    yield {
        "url": f"http://{COMPAT_REF}.maludb.local:{GATEWAY_PORT}",
        "key": issued.plaintext,
        "mailbox": f"http://127.0.0.1:{MAILBOX_PORT}/",
        # Phase 12 slice 5: what the MaluDB data-model cases need beyond the client.
        "project_id": project_id,
        "key_ring": key_ring,
        "jwt_secret": settings.jwt_secret,
        "gateway_config": gateway_config,
    }

    server.should_exit = True
    mailbox.shutdown()
    postgrest.terminate()
    postgrest.wait(timeout=10)
    gotrue.terminate()
    gotrue.wait(timeout=10)
    admin_conn.close()
    with psycopg.connect(ADMIN_DSN, autocommit=True) as admin:
        admin.execute(f'DROP DATABASE IF EXISTS "{names.database}" WITH (FORCE)')
        for role in (names.authenticator, names.auth, names.admin):
            admin.execute(f'DROP ROLE IF EXISTS "{role}"')
    shutil.rmtree(config_dir, ignore_errors=True)


@pytest.fixture(scope="module")
def compat_results(compat_stack):
    """Run the official client once; every test reads one case from the output."""
    completed = subprocess.run(  # noqa: S603 - fixed argv
        [shutil.which("node") or "node", str(COMPAT_DIR / "suite.mjs")],  # noqa: S607
        cwd=COMPAT_DIR,
        capture_output=True,
        text=True,
        timeout=180,
        env={**os.environ, "MALUDB_URL": compat_stack["url"], "MALUDB_KEY": compat_stack["key"],
             "MALUDB_MAILBOX": compat_stack["mailbox"], "MALUDB_TENANT_RPC": ",".join(TENANT_RPC)},
        check=False,
    )
    cases = {}
    for line in completed.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            row = json.loads(line)
            cases[row["name"]] = row
    if not cases:
        pytest.fail(f"the client suite produced no results.\nstdout:\n{completed.stdout}\n"
                    f"stderr:\n{completed.stderr}")
    return cases


# One test per behaviour rather than one for the whole suite: a single failing
# operation should name itself, and `specs/compatibility-matrix.yaml` is
# promoted per feature, so the evidence has to be per feature too.
@pytest.mark.parametrize(
    "case",
    [
        "select", "insert", "insert many", "update", "upsert", "filters",
        "ordering", "range and limit", "count", "rpc", "delete",
        "rls hides another tenant-scoped row",
        "a table created after the worker started is visible",
        "extension functions are not exposed as rpc",
        # Phase 04 slice 2. Driven through the same client and gateway, so what
        # is proven is that `supabase.auth` works against MaluDB rather than
        # that our reading of GoTrue's wire format is right.
        "auth signup",
        # The journey every real end user takes, and the part only the official
        # client can answer: what a migrated application sees before the link is
        # clicked. Phase 04's own end-to-end test drives GoTrue over raw HTTP,
        # so it cannot report how supabase-js surfaces an unconfirmed user.
        "an unconfirmed user cannot sign in",
        "following the confirmation link enables sign-in",
        "auth signin password",
        "auth token carries the claims RLS needs",
        "auth get user",
        "auth session refresh",
        "auth signout",
        "a wrong password is refused",
        # Phase 04 slice 3. Phase 03 could only claim RLS for anonymous
        # callers; these resolve auth.uid() from a GoTrue-issued token that
        # travelled through the gateway.
        "rls two signed-in users are distinguished",
        "rls refuses a row claimed for another user",
        "rls hides signed-in rows from an anonymous caller",
        # ADR-076. Refused as `permission denied` for every customer role until
        # grants slice 1: pgvector through RPC, a uuid-ossp default and a
        # pgcrypto trigger, as anon and as a signed-in user.
        "vector search through a migrated match_documents rpc",
        "vector search as a signed-in user",
        "a uuid default and a crypt trigger work for a signed-in user",
        "every extension function the data api describes is refused",
    ],
)
def test_official_client(compat_results, case):
    result = compat_results.get(case)
    assert result is not None, f"the client suite never ran {case!r}"
    assert result["ok"], f"{case}: {result.get('error')}"


# -- Phase 12 slice 5: the MaluDB data-model graph, through the official client ----


def _node_suite(script: str, env: dict) -> dict:
    completed = subprocess.run(  # noqa: S603 - fixed argv
        [shutil.which("node") or "node", str(COMPAT_DIR / script)],  # noqa: S607
        cwd=COMPAT_DIR, capture_output=True, text=True, timeout=120,
        env={**os.environ, **env}, check=False,
    )
    cases = {}
    for line in completed.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            row = json.loads(line)
            cases[row["name"]] = row
    if not cases:
        pytest.fail(f"{script} produced no results.\nstdout:\n{completed.stdout}\n"
                    f"stderr:\n{completed.stderr}")
    return cases


@pytest.fixture(scope="module")
def maludb_compat(compat_stack):
    """Before and after, on one real project, the way a customer gets there.

    Enabled and refreshed through the platform's own routes and its own worker --
    not by calling `maludb.enable` directly -- because the claim is about the
    product a customer uses: ask, wait, then read with the official client.
    """
    import datetime as dt
    import uuid

    import jwt
    from fastapi.testclient import TestClient
    from psycopg.types.json import Jsonb

    from services.control_plane import nodes, provisioner
    from services.control_plane.main import create_app as create_control_plane
    from services.gateway import app as gateway_app
    from tests.conftest import TEST_CREDENTIAL

    project_id = compat_stack["project_id"]
    key_ring = compat_stack["key_ring"]
    with db.connection() as conn:
        node = db.one(
            conn,
            "INSERT INTO nodes (name, hostname, internal_host, node_pool, status, last_health_at) "
            "VALUES ('compat-node', 'compat.example', '127.0.0.1', 'shared', 'active', now()) "
            "ON CONFLICT (name) DO UPDATE SET status = 'active' RETURNING id",
        )["id"]
        nodes.set_admin_dsn(conn, name="compat-node", dsn=ADMIN_DSN, key_ring=key_ring)
        db.execute(conn, "UPDATE projects SET node_id = %s WHERE id = %s", (node, project_id))
        # Two an hour: enabling draws on the same budget, so enable + one refresh
        # spends it, and the next refresh is the one that must be refused.
        db.execute(conn, "UPDATE plans SET config_json = %s WHERE code = 'compat'",
                   (Jsonb({"limits": {"datamodel_refreshes_per_hour": 2}}),))
        secret = api_keys.create(conn, project_id=project_id, key_type=api_keys.SECRET,
                                 pepper=TEST_PEPPER).plaintext
        conn.commit()

    user_jwt = jwt.encode(
        {"sub": str(uuid.uuid4()), "role": "authenticated", "aud": "authenticated",
         "exp": dt.datetime.now(dt.UTC) + dt.timedelta(minutes=30)},
        compat_stack["jwt_secret"], algorithm="HS256",
    )
    env = {"MALUDB_URL": compat_stack["url"], "MALUDB_KEY": compat_stack["key"],
           "MALUDB_SECRET_KEY": secret, "MALUDB_USER_JWT": user_jwt}

    before = _node_suite("maludb.mjs", {**env, "MALUDB_PHASE": "before"})

    def run_worker() -> dict:
        assert provisioner.run_maludb_once(key_ring=key_ring), "the provisioner found no job"
        with db.connection() as conn:
            return db.one(conn, "SELECT state, detail FROM maludb_jobs ORDER BY id DESC LIMIT 1")

    with TestClient(create_control_plane(compat_stack["gateway_config"])) as control_plane:
        token = control_plane.post(
            "/v1/auth/signin", json={"email": f"{COMPAT_REF}@example.com", "password": TEST_CREDENTIAL}
        ).json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        enable = control_plane.post(f"/v1/projects/{COMPAT_REF}/maludb/datamodel/enable", headers=headers)
        enabled_job = run_worker()
        refresh = control_plane.post(f"/v1/projects/{COMPAT_REF}/maludb/datamodel/refresh", headers=headers)
        refreshed_job = run_worker()
        over = control_plane.post(f"/v1/projects/{COMPAT_REF}/maludb/datamodel/refresh", headers=headers)
        status = control_plane.get(f"/v1/projects/{COMPAT_REF}/maludb/datamodel", headers=headers).json()
    # Leaving the control plane's TestClient runs its lifespan shutdown, which
    # closes the process-wide connection pool -- the same pool the in-process
    # gateway reads projects and keys through. Without this every request after
    # this point answers 500, which reads exactly like enabling having broken the
    # project's Data API. (It had not: PostgREST, asked directly, served public
    # and maludb alike.)
    db.init_pool(compat_stack["gateway_config"].database_url)

    # The gateway caches a project's row briefly, so a newly enabled project is
    # refused by name for up to this long. Waited out rather than reached into:
    # it is exactly what a customer sees, and docs/MALUDB-FEATURES.md says so.
    time.sleep(gateway_app.PROJECT_CACHE_TTL_SECONDS + 0.5)
    after = _node_suite("maludb.mjs", {**env, "MALUDB_PHASE": "after"})

    # Slice 6: off again, through the same route and worker, and read once more.
    with TestClient(create_control_plane(compat_stack["gateway_config"])) as control_plane:
        token = control_plane.post(
            "/v1/auth/signin", json={"email": f"{COMPAT_REF}@example.com", "password": TEST_CREDENTIAL}
        ).json()["token"]
        disable = control_plane.post(f"/v1/projects/{COMPAT_REF}/maludb/datamodel/disable",
                                     headers={"Authorization": f"Bearer {token}"})
    db.init_pool(compat_stack["gateway_config"].database_url)  # see the note above
    disabled_job = run_worker()
    time.sleep(gateway_app.PROJECT_CACHE_TTL_SECONDS + 0.5)
    withdrawn = _node_suite("maludb.mjs", {**env, "MALUDB_PHASE": "withdrawn"})

    return {
        "before": before, "after": after, "enable": enable, "enabled_job": enabled_job,
        "refresh": refresh, "refreshed_job": refreshed_job, "over": over, "status": status,
        "disable": disable, "disabled_job": disabled_job, "withdrawn": withdrawn,
    }


def test_the_maludb_schema_is_refused_by_name_before_it_is_enabled(maludb_compat):
    case = maludb_compat["before"]["the maludb schema is refused on a project that has not enabled it"]
    assert case["ok"], case.get("error")


def test_a_customer_enables_and_refreshes_through_the_platform(maludb_compat):
    assert maludb_compat["enable"].status_code == 202, maludb_compat["enable"].text
    assert maludb_compat["enabled_job"]["state"] == "succeeded", maludb_compat["enabled_job"]["detail"]
    assert maludb_compat["refresh"].status_code == 202, maludb_compat["refresh"].text
    assert maludb_compat["refreshed_job"]["state"] == "succeeded", maludb_compat["refreshed_job"]["detail"]
    assert maludb_compat["status"]["enabled"] is True


def test_a_refresh_over_the_plans_limit_is_refused(maludb_compat):
    over = maludb_compat["over"]
    assert over.status_code == 429, over.text
    assert int(over.headers["retry-after"]) > 0


@pytest.mark.parametrize(
    "case",
    [
        "service_role reads the copy",
        "the copy carries a description of each relation",
        "the graph edges are readable and joined to their nodes",
        "anon is refused the copy",
        "a signed-in user is refused the copy",
        "the public Data API still answers",
    ],
)
def test_the_data_model_graph_through_the_official_client(maludb_compat, case):
    result = maludb_compat["after"].get(case)
    assert result is not None, f"the client suite never ran {case!r}"
    assert result["ok"], f"{case}: {result.get('error')}"


def test_enabling_extends_the_public_surface_and_alters_none_of_it(maludb_compat):
    """ADR-074's compatibility promise, measured rather than stated: the `public`
    schema's OpenAPI description is identical before and after enabling."""
    before = maludb_compat["before"]["public surface"]
    after = maludb_compat["after"]["public surface"]
    assert before["ok"] and after["ok"], (before.get("error"), after.get("error"))
    assert after["data"] == before["data"], "enabling the data-model graph changed what public publishes"


def test_a_customer_turns_it_off_and_the_client_is_refused_by_name_again(maludb_compat):
    """Off is withdrawal: the schema leaves the Data API, and nothing in public moves."""
    assert maludb_compat["disable"].status_code == 202, maludb_compat["disable"].text
    assert maludb_compat["disabled_job"]["state"] == "succeeded", maludb_compat["disabled_job"]["detail"]
    for case in ("a disabled project refuses the maludb schema by name again",
                 "the public Data API still answers after disabling"):
        result = maludb_compat["withdrawn"][case]
        assert result["ok"], f"{case}: {result.get('error')}"
    assert maludb_compat["withdrawn"]["public surface"]["data"] == maludb_compat["before"]["public surface"]["data"]

