#!/usr/bin/env python3
"""Regenerate specs/control-plane-api.yaml from the FastAPI application.

ADR-024: the application is authoritative for the API contract. CI runs this
with --check and fails on drift, so the committed spec stays reviewable in
pull requests without being hand-maintained.

  scripts/export-openapi.py           # rewrite the spec
  scripts/export-openapi.py --check   # exit 1 if the spec is stale
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "specs" / "control-plane-api.yaml"

sys.path.insert(0, str(REPO_ROOT))

HEADER = """# Generated by scripts/export-openapi.py -- do not edit by hand.
#
# ADR-024: the FastAPI application is authoritative for this contract. CI fails
# if this file drifts from the app. To change the API, change the routes and
# regenerate.
#
# THIS IS THE PUBLIC SURFACE (ADR-037). It is generated from
# `create_public_app`, which mounts only the routers classified as reachable
# from the internet, so this file is the contract a customer's client is written
# against. Internal routes -- today, GoTrue's send-email hook, which a project's
# Auth worker calls on a node -- are served by `create_app` on a separate
# listener and deliberately do not appear here.
#
# Authentication is declared and enforced: `platformCredential` is a real
# FastAPI dependency, and every route that touches data depends on it. The
# schemes are described in docs/ACCOUNTS.md (ADR-021).
"""

# No security schemes are injected here, and none need to be.
#
# An earlier version declared sessionToken and personalAccessToken and a global
# security requirement, even though no route enforced them. A security review
# found that this makes the published contract assert a control the application
# does not implement: a generated client would attach a bearer token that is
# never checked, and the CI drift check cannot catch the divergence because it
# compares routes, not security behaviour.
#
# Phase 01 slice 2 registered them as real FastAPI dependencies, so FastAPI now
# emits `platformCredential` into this spec on its own and the contract matches
# behaviour because it is generated from it.


def build_spec() -> str:
    import yaml

    # Configuration the app needs to construct; never contacted.
    os.environ.setdefault("MALUDB_ENV", "development")
    os.environ.setdefault("MALUDB_CONTROL_PLANE_DATABASE_URL", "postgresql://spec:spec@127.0.0.1/spec")
    os.environ.setdefault("MALUDB_DOCS_ENABLED", "1")

    from services.control_plane.config import Config

    cfg = Config(
        environment="development",
        database_url="postgresql://spec:spec@127.0.0.1/spec",
        gateway_domain="maludb.local",
        docs_enabled=True,
        kek=b"0" * 32,
        token_pepper=b"0" * 32,
    )

    # The *public* application (ADR-037): this contract describes what a
    # customer's client may call. Generating it from the internal application
    # would publish a document whose routes a public client cannot reach, which
    # is a worse kind of wrong than an incomplete one.
    from services.control_plane.main import create_public_app

    spec = create_public_app(cfg).openapi()
    return HEADER + yaml.safe_dump(spec, sort_keys=True, default_flow_style=False, width=100)


def main() -> int:
    generated = build_spec()
    check = "--check" in sys.argv

    if check:
        if not SPEC_PATH.exists():
            print(f"{SPEC_PATH} is missing; run scripts/export-openapi.py", file=sys.stderr)
            return 1
        if SPEC_PATH.read_text() != generated:
            print(
                "specs/control-plane-api.yaml is out of date with the FastAPI app.\n"
                "Run: scripts/export-openapi.py",
                file=sys.stderr,
            )
            return 1
        print("OpenAPI spec is in sync")
        return 0

    SPEC_PATH.write_text(generated)
    print(f"wrote {SPEC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
