#!/usr/bin/env python3
"""Regenerate specs/control-plane-api.yaml from the FastAPI application.

ADR-024: the application is authoritative for the API contract. CI runs this
with --check and fails on drift, so the committed spec stays reviewable in
pull requests without being hand-maintained.

  scripts/export-openapi.py           # rewrite the spec
  scripts/export-openapi.py --check   # exit 1 if the spec is stale
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "specs" / "control-plane-api.yaml"

sys.path.insert(0, str(REPO_ROOT))

HEADER = """# Generated by scripts/export-openapi.py -- do not edit by hand.
#
# ADR-024: the FastAPI application is authoritative for this contract. CI fails
# if this file drifts from the app. To change the API, change the routes and
# regenerate.
#
# NO AUTHENTICATION IS DECLARED OR ENFORCED YET. These routes are unauthenticated
# and the service refuses to start with MALUDB_ENV=production for that reason.
# Platform-user authentication -- sessions and personal access tokens, described
# in docs/ACCOUNTS.md -- lands in Phase 01 slice 2 and will appear here once the
# application actually enforces it.
"""

# No security schemes are injected here.
#
# An earlier version declared sessionToken and personalAccessToken and a global
# security requirement, even though no route enforced them. A security review
# found that this makes the published contract assert a control the application
# does not implement: a generated client would attach a bearer token that is
# never checked, and the CI drift check cannot catch the divergence because it
# compares routes, not security behaviour.
#
# The schemes are specified in docs/ACCOUNTS.md and remain the intended design.
# Slice 2 registers them as real FastAPI dependencies, at which point FastAPI
# emits them into this spec on its own and contract matches behaviour.


def build_spec() -> str:
    import yaml

    # Configuration the app needs to construct; never contacted.
    os.environ.setdefault("MALUDB_ENV", "development")
    os.environ.setdefault("MALUDB_CONTROL_PLANE_DATABASE_URL", "postgresql://spec:spec@127.0.0.1/spec")
    os.environ.setdefault("MALUDB_DOCS_ENABLED", "1")

    from services.control_plane.config import Config

    cfg = Config(
        environment="development",
        database_url="postgresql://spec:spec@127.0.0.1/spec",
        gateway_domain="maludb.local",
        docs_enabled=True,
        kek=b"0" * 32,
        token_pepper=b"0" * 32,
    )

    from services.control_plane.main import create_app

    spec = create_app(cfg).openapi()
    return HEADER + yaml.safe_dump(spec, sort_keys=True, default_flow_style=False, width=100)


def main() -> int:
    generated = build_spec()
    check = "--check" in sys.argv

    if check:
        if not SPEC_PATH.exists():
            print(f"{SPEC_PATH} is missing; run scripts/export-openapi.py", file=sys.stderr)
            return 1
        if SPEC_PATH.read_text() != generated:
            print(
                "specs/control-plane-api.yaml is out of date with the FastAPI app.\n"
                "Run: scripts/export-openapi.py",
                file=sys.stderr,
            )
            return 1
        print("OpenAPI spec is in sync")
        return 0

    SPEC_PATH.write_text(generated)
    print(f"wrote {SPEC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
