#!/bin/bash
# Phase 00 spike harness — provision one throwaway tenant database.
#
# This is a SPIKE ARTEFACT, not production provisioning. It exists so the
# Phase 00 results in tasks/PHASE-00-FEASIBILITY.md can be reproduced, and as a
# reference implementation of specs/tenant-role-model.md. Production
# provisioning belongs in the control plane (Phase 02), not in a shell script.
#
# Safe only on a development node. It creates and drops databases and roles.
# Requires: passwordless `sudo -u postgres`, openssl.
#
# Usage: scripts/spike-provision-tenant.sh [project_ref]

set -euo pipefail

REF="${1:-sp$(openssl rand -hex 3)}"
[[ "$REF" =~ ^[a-z0-9]{4,16}$ ]] || { echo "project_ref must be [a-z0-9]{4,16}"; exit 1; }
DB="mldb_$REF"
P="sudo -n -u postgres psql -q -v ON_ERROR_STOP=1"
OUT="${TMPDIR:-/tmp}/$DB.env"

# AGENTS.md: API keys and database passwords must be generated cryptographically
AUTHENTICATOR_PW=$(openssl rand -hex 24)
AUTH_PW=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)

echo "== node-level shared role names (idempotent, once per node) =="
$P <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon')          THEN CREATE ROLE anon NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF;
  -- BYPASSRLS is safe here ONLY because service_role is NOLOGIN and every session
  -- is already bound to one database by the ADR-014 CONNECT lockdown.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role')  THEN CREATE ROLE service_role NOLOGIN BYPASSRLS; END IF;
END $$;
SQL

echo "== per-project roles =="
$P <<SQL
CREATE ROLE ${DB}_authenticator LOGIN PASSWORD '$AUTHENTICATOR_PW' CONNECTION LIMIT 20 NOINHERIT;
CREATE ROLE ${DB}_auth          LOGIN PASSWORD '$AUTH_PW'          CONNECTION LIMIT 10;
CREATE ROLE ${DB}_admin         NOLOGIN;
GRANT anon, authenticated, service_role TO ${DB}_authenticator;
SQL

echo "== database, owned by the platform role =="
sudo -n -u postgres createdb -O postgres "$DB"

echo "== ADR-014 lockdown (mandatory: PUBLIC has CONNECT by default) =="
$P <<SQL
REVOKE CONNECT ON DATABASE $DB FROM PUBLIC;
GRANT  CONNECT ON DATABASE $DB TO ${DB}_authenticator, ${DB}_auth;
SQL

echo "== ADR-015: maludb_core in every tenant database =="
$P -d "$DB" -c "CREATE EXTENSION maludb_core CASCADE" >/dev/null 2>&1
$P -d "$DB" -tAc "SELECT 'maludb_core ' || maludb_core.maludb_core_version()"

echo "== bootstrap: auth helpers + example table =="
$P -d "$DB" <<'SQL'
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT coalesce(nullif(current_setting('request.jwt.claims', true),'')::jsonb, '{}'::jsonb) $$;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT nullif(auth.jwt() ->> 'sub','')::uuid $$;
CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$
  SELECT auth.jwt() ->> 'role' $$;
CREATE OR REPLACE FUNCTION auth.email() RETURNS text LANGUAGE sql STABLE AS $$
  SELECT auth.jwt() ->> 'email' $$;

-- PHASE-00 finding 6: BY DEFAULT, never ALWAYS, or .upsert() breaks
CREATE TABLE public.customers (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id   uuid NOT NULL DEFAULT auth.uid(),
  name       text NOT NULL,
  email      text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY customers_all ON public.customers FOR ALL TO authenticated
  USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

CREATE FUNCTION public.customer_count() RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT count(*) FROM public.customers $$;

GRANT USAGE ON SCHEMA public, auth TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_count() TO anon, authenticated;
SQL

echo "== PHASE-00 finding 2: revoke extension functions off the public API surface =="
$P -d "$DB" <<'SQL'
DO $$
DECLARE r record; n int := 0;
BEGIN
  FOR r IN SELECT p.oid::regprocedure AS sig
             FROM pg_proc p
             JOIN pg_namespace ns ON ns.oid = p.pronamespace
             JOIN pg_depend d  ON d.objid = p.oid AND d.deptype = 'e'
            WHERE ns.nspname = 'public'
  LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', r.sig);
    n := n + 1;
  END LOOP;
  RAISE NOTICE 'revoked EXECUTE on % extension functions in public', n;
END $$;
SQL

echo "== PHASE-00 findings 4/5: keep GoTrue bookkeeping out of the exposed schema =="
$P <<SQL
GRANT CREATE ON DATABASE $DB TO ${DB}_auth;
ALTER ROLE ${DB}_auth IN DATABASE $DB SET search_path = auth, public;
SQL
# these are per-database objects, so they must be applied inside $DB
$P -d "$DB" -c "ALTER SCHEMA auth OWNER TO ${DB}_auth;
                ALTER FUNCTION auth.uid() OWNER TO ${DB}_auth;
                ALTER FUNCTION auth.jwt() OWNER TO ${DB}_auth;
                ALTER FUNCTION auth.role() OWNER TO ${DB}_auth;
                ALTER FUNCTION auth.email() OWNER TO ${DB}_auth;"

echo "== ADR-017: plan limits on the LOGIN role, IN DATABASE =="
$P <<SQL
ALTER ROLE ${DB}_authenticator IN DATABASE $DB SET statement_timeout = '8s';
ALTER ROLE ${DB}_authenticator IN DATABASE $DB SET idle_in_transaction_session_timeout = '30s';
SQL

umask 077
cat > "$OUT" <<EOF
DB=$DB
AUTHENTICATOR_PW=$AUTHENTICATOR_PW
AUTH_PW=$AUTH_PW
JWT_SECRET=$JWT_SECRET
EOF

cat <<EOF

== provisioned $DB ==
generated credentials: $OUT   (mode 600, outside the repo - never commit)

next:
  postgrest with db-uri postgres://${DB}_authenticator:<pw>@127.0.0.1:5432/$DB
                 db-anon-role anon, db-schemas public, jwt-secret <JWT_SECRET>
  gotrue  with DATABASE_URL postgres://${DB}_auth:<pw>@127.0.0.1:5432/$DB
                 GOTRUE_DB_NAMESPACE=auth, GOTRUE_JWT_SECRET=<JWT_SECRET>
  remember: NOTIFY pgrst, 'reload schema'  after any tenant DDL

teardown:
  sudo -u postgres psql -c "DROP DATABASE $DB"
  sudo -u postgres psql -c "DROP ROLE ${DB}_authenticator, ${DB}_auth, ${DB}_admin"
EOF
